### PR TITLE
MLJ GSOC 20201

### PR DESCRIPTION
**Pull request by darenasc**
Projects for 2021

### CODE REVIEW

**Comment by darenasc** [comment]
please consider this PR that contains the #1185 content and expanding on it.

**Comment by logankilpatrick** [comment]
So the other one can be closed?

**Comment by darenasc** [comment]
@vollmersj, yes.

**Comment by logankilpatrick** [comment]
Great, thanks!

**Comment by KristofferC** [comment]
What does the `content/jsoc/gsoc/MLJ.md` file do? It is currently causing `serve()` to error (ref #1207) because of the `# {{< get_param title >}}` part. It is also the only file in the `content` directory. Should it be removed?

**Comment by darenasc** [comment]
thanks @KristofferC, yes you can remove it, the projects are on the `jsoc/gsoc/MLJ.md` file. I could update the one in content if necessary.

**Pull request merged**
