### PR TITLE
the legal data page is no longer needed

### PR DESCRIPTION
**Pull request by StefanKarpinski**
There are no longer any Julia versions in use that send any data that requires this legal data notice, so I'm taking it down. We should, however, have some kind of legal notice here, but that's work for another PR.

### CODE REVIEW

**Comment by ViralBShah** [comment]
I suggest removing it altogether for now. When we have a legal page can always add it back.

**Comment by StefanKarpinski** [comment]
Will it break the formatting of the footer if I delete a row from one of the columns?

**Comment by logankilpatrick** [comment]
Check the PR preview link above, looks good to me.

**Comment by ViralBShah** [comment]
No the footer formatting won't break.

**Comment by StefanKarpinski** [comment]
I left the placeholder `/legal/` page and removed the link to it. Makes it easier to put something there.

**Pull request merged**
