### PR TITLE
Make juliaup instructions simpler

### PR DESCRIPTION
**Pull request by IanButterworth**
Simplifies the instructions and makes them automatically detect platform (with an override)

Closes https://github.com/JuliaLang/www.julialang.org/issues/658

PR
https://julialang.netlify.app/previews/pr2005/downloads/

Currently
Screenshot 2024-01-01 at 8 53 57 PM

### CODE REVIEW

**Review by StefanKarpinski — APPROVED** [review]

**Comment by LilithHafner** [comment]
I have not verified that the platform detection works on windows, but from Linux this GUI looks much better than before. Thanks!

**Comment by giordano** [comment]
It'd be nice to see the instructions for another operating system without having the other operating system.  Like, having multiple tabs for the different OSes, with the current one open by default.

**Comment by giordano** [comment]
One example: https://rustup.rs/ (but I'd prefer the tabs instead of this).

**Comment by IanButterworth** [comment]
There's a link underneath the code block for that. Did you not see that?

**Comment by IanButterworth** [comment]
Discussed with @giordano on slack and he had missed the existing text. Tabs seem like a good idea but that could be tried out in another PR.

As for windows, I checked in a cross-platform browser checker and it looks good
Screenshot 2024-01-02 at 4 55 36 PM

**Comment by KristofferC** [comment]
The

> This recommended installation method is via the [Juliaup](https://github.com/JuliaLang/juliaup) installation manager, which will automatically install julia and help keep it up to date.

feels unclear to me when it comes after the installation instructions. Because it isn't clear that the above command is in fact installing and using Julia up. Maybe it could be something like:


> This will install the [Juliaup](https://github.com/JuliaLang/juliaup) installation manager, which will itself automatically install julia and help keep it up to date.

**Pull request merged**
