### PR TITLE
GSoC proposal: multivariate data analysis

### PR DESCRIPTION
**Pull request by mateuszbaran**
I would like to submit a proposal for a GSoC project. It is intended to be a new package, a more modern version of MultivariateStats.jl. What do you think? I've initially consulted the idea with @ParadaCarleton and @kellertuer . I think @sethaxen may also be interested.

I will publish my initial code soon on MIT license, most likely under the name `MultivariateDataAnalysis`.

EDIT: Here is a very early version of the package: https://github.com/JuliaManifolds/MultivariateDataAnalysis.jl .

### CODE REVIEW

**Comment by logankilpatrick** [comment]
Hey! This is not the right place for proposals, please contact the mentors directly.

**Comment by logankilpatrick** [comment]
Sorry, I was very confused on this, this seemed like it was a contributor proposal for GSoC, not a mentor proposal haha, This looks all good, please just add a link here: https://julialang.org/jsoc/projects/

**Comment by mateuszbaran** [comment]
Thanks, I've added a link in project list.

**Comment by mateuszbaran** [comment]
It looks like it's past the deadline and this wasn't merged, so there seems to be no reason to keep this PR open.

**Pull request closed without merging**
