### PR TITLE
Adapt fluxdifffeq blog post to Hugo

### PR DESCRIPTION
**Pull request by goggle**
Adapts the blog post https://julialang.org/blog/2019/01/fluxdiffeq/ to the new Hugo syntax.

### CODE REVIEW

**Comment by logankilpatrick** [comment]
Thanks!

**Comment by logankilpatrick** [comment]
Probably should have merge #582

**Comment by goggle** [comment]
Hmm, I think we need both, don't we?
If I understand this correctly, #582 updates the programming syntax, my PR updates the syntax to render the blog post.

**Comment by logankilpatrick** [comment]
This PR just broke the post so I reverted.

**Comment by logankilpatrick** [comment]
I will try again after I merge Chris's PR.

**Comment by logankilpatrick** [comment]
Okay, can you try again @goggle

**Comment by ChrisRackauckas** [comment]
I updated just the code syntax and not much else

**Comment by ChrisRackauckas** [comment]
I would be very surprised if that was the issue

**Pull request merged**
