### PR TITLE
Add some publications

### PR DESCRIPTION
**Pull request by timholy**
I've been terrible about remembering to add publications, but here are a couple.

### CODE REVIEW

**Comment by tlienart** [comment]
@timholy are you happy if I take over this PR? I'll discard the abstracts as the current build system doesn't use that but otherwise will keep things unchanged

**Comment by timholy** [comment]
Certainly! I wasn't sure what the reason for the holdup was.

**Comment by tlienart** [comment]
Cool, well the PR happened right  at the time where we switched the backend so I guess there was uncertainty around how to merge this PR 😄 ;

**Comment by logankilpatrick** [comment]
@timholy, sorry for not merging sooner. I thought you were still adding stuff or the like so I didn’t merge it in.

**Comment by tlienart** [comment]
Please don't merge now though 😱 it needs to be adapted to the new thing, I'll open a PR soon

**Comment by tlienart** [comment]
closing this in favour of #682

**Pull request closed without merging**
