### PR TITLE
Add link to julia docker images on the download page.

### PR DESCRIPTION
**Pull request by fredrikekre**
xref https://github.com/docker-library/julia/issues/28, cc @tianon, @yosifkit

### CODE REVIEW

**Comment by ViralBShah** [comment]
Do we know how these images are created? Are they based on our binaries? And passing all tests? I believe so - but just want to make sure.

**Comment by ImreSamu** [comment]
2 Dockerfile example :
* https://github.com/docker-library/julia/blob/master/1.1/stretch/Dockerfile
* https://github.com/docker-library/julia/blob/master/1.1/windows/windowsservercore-1803/Dockerfile

@tianon 
simple test:    `docker run -it --rm julia:1.0.3 julia -e 'Base.runtests()'`
* imho:  the  Julia `"Sockets"` test is sensitive for IPv6   ( so need good [  IPv6 support for the Docker daemon](https://docs.docker.com/config/daemon/ipv6/)  AND  ` --fixed-cidr-v6` )

**Comment by ViralBShah** [comment]
Thanks. If you are using the official binaries, I think there is no need to run the tests.

**Comment by tianon** [comment]
I figured, but just in case, I've run the tests on a fresh build of our 1.1 `Dockerfile` using `--sysctl net.ipv6.conf.all.disable_ipv6=0` (so we get an IPv6 link-local address back...  thanks Docker, so helpful), and got the following result: (after it sucked up a huge amount of RAM and CPU for a while :sweat_smile:)

```console
Test                          (Worker) | Time (s) | GC (s) | GC % | Alloc (MB) | RSS (MB)
compiler/irpasses                  (6) |     0.90 |   0.06 |  6.8 |     157.79 |   228.06
compiler/validation                (4) |     1.15 |   0.07 |  6.0 |     158.68 |   228.06
compiler/ssair                     (5) |     1.47 |   0.02 |  1.2 |      68.28 |   228.06
      From worker 2:	Skipping Base.Filesystem.JL_O_RANDOM
      From worker 2:	Skipping Base.Filesystem.JL_O_SEQUENTIAL
      From worker 2:	Skipping Base.Filesystem.JL_O_SHORT_LIVED
      From worker 2:	Skipping Base.Filesystem.JL_O_TEMPORARY
      From worker 2:	Skipping Base.active_repl
      From worker 2:	Skipping Base.active_repl_backend
compiler/codegen                   (7) |     2.39 |   0.17 |  7.2 |     190.20 |   239.63
compiler/inline                    (6) |     0.47 |   0.04 |  8.0 |      44.79 |   228.06
strings/search                     (7) |     1.28 |   0.02 |  1.5 |     124.69 |   239.63
strings/util                       (6) |     1.47 |   0.03 |  1.9 |     223.59 |   230.61
      From worker 2:	Skipping Base.active_repl
      From worker 2:	Skipping Base.active_repl_backend
strings/io                         (7) |     0.77 |   0.02 |  2.4 |     124.30 |   242.89
unicode/utf8                       (7) |     0.04 |   0.00 |  8.0 |       3.80 |   242.98
      From worker 2:	Skipping Base.Filesystem.JL_O_RANDOM
      From worker 2:	Skipping Base.Filesystem.JL_O_SEQUENTIAL
      From worker 2:	Skipping Base.Filesystem.JL_O_SHORT_LIVED
      From worker 2:	Skipping Base.Filesystem.JL_O_TEMPORARY
      From worker 2:	Skipping Base.active_repl
      From worker 2:	Skipping Base.active_repl_backend
ambiguous                          (2) |     5.17 |   0.16 |  3.1 |    1025.77 |   253.72
compiler/inference                 (3) |     5.49 |   0.19 |  3.5 |     739.25 |   268.87
worlds                             (2) |     0.86 |   0.05 |  6.4 |     112.62 |   253.72
strings/basic                      (5) |     4.76 |   0.11 |  2.4 |     577.33 |   238.88
strings/types                      (6) |     2.24 |   0.10 |  4.5 |    1223.72 |   244.07
keywordargs                        (3) |     1.20 |   0.02 |  1.8 |     116.91 |   272.02
triplequote                        (3) |     0.02 |   0.00 |  0.0 |       1.77 |   272.50
intrinsics                         (3) |     0.27 |   0.00 |  1.3 |      29.65 |   273.13
char                               (6) |     0.87 |   0.06 |  6.4 |     146.07 |   246.21
hashing                            (6) |    13.63 |   0.36 |  2.7 |    1693.03 |   280.64
iobuffer                           (6) |     1.00 |   0.03 |  2.6 |     117.09 |   300.17
dict                               (3) |    16.55 |   0.56 |  3.4 |    2009.04 |   333.32
subtype                            (5) |    17.34 |   0.49 |  2.8 |    1835.55 |   729.28
staged                             (6) |     3.07 |   0.14 |  4.5 |     342.84 |   301.11
tuple                              (6) |     2.23 |   0.06 |  2.9 |     274.05 |   305.90
reduce                             (6) |     7.63 |   0.44 |  5.7 |    1285.00 |   460.44
core                               (7) |    36.06 |   3.87 | 10.7 |   11187.60 |   647.29
numbers                            (2) |    38.87 |   1.01 |  2.6 |    4875.63 |   380.09
intfuncs                           (2) |     1.07 |   0.04 |  3.3 |     120.02 |   380.09
simdloop                           (2) |     1.57 |   0.08 |  5.0 |     280.79 |   383.16
offsetarray                        (3) |    25.81 |   1.35 |  5.2 |    4171.27 |   413.94
vecelement                         (2) |     5.01 |   0.38 |  7.5 |    1375.35 |   393.53
rational                           (3) |     6.18 |   0.30 |  4.9 |     908.73 |   440.48
reducedim                          (6) |    21.94 |   0.91 |  4.2 |    3321.57 |   460.44
copy                               (3) |     1.38 |   0.07 |  5.0 |     190.59 |   445.30
fastmath                           (3) |     5.66 |   0.20 |  3.5 |     600.99 |   465.66
functional                         (3) |     4.65 |   0.27 |  5.7 |     663.55 |   470.31
abstractarray                      (7) |    39.45 |   2.32 |  5.9 |    5388.11 |   647.29
operators                          (7) |     3.65 |   0.25 |  6.7 |     574.39 |   647.29
path                               (7) |     1.30 |   0.05 |  4.0 |     105.35 |   647.29
math                               (6) |    31.26 |   0.81 |  2.6 |    3039.55 |   460.44
arrayops                           (5) |    66.78 |   3.39 |  5.1 |   10589.55 |   842.56
parse                              (6) |     2.74 |   0.11 |  3.9 |     363.64 |   460.44
bigint                             (6) |     2.49 |   0.10 |  4.0 |     282.07 |   460.44
iterators                          (3) |    26.89 |   1.34 |  5.0 |    3932.47 |   553.66
      From worker 3:	       [stdio passthrough ok]
spawn                              (3) |    12.10 |   0.17 |  1.4 |     370.71 |   574.63
[ Info: 
backtrace                          (3) |     0.81 |   0.03 |  4.3 |      75.35 |   574.63
exceptions                         (3) |     0.32 |   0.01 |  2.8 |      33.65 |   574.63
      From worker 5:	WARNING: replacing module Foo.
loading                            (5) |    20.24 |   1.59 |  7.8 |    4368.83 |   842.56
file                               (3) |     2.82 |   0.11 |  4.0 |     255.93 |   576.49
version                            (3) |     0.95 |   0.06 |  6.8 |     136.45 |   576.86
namedtuple                         (3) |     2.29 |   0.11 |  4.7 |     221.61 |   578.05
sorting                            (6) |    22.55 |   0.85 |  3.8 |    2297.14 |   517.81
mpfr                               (3) |     5.73 |   0.30 |  5.2 |    1090.66 |   597.42
complex                            (3) |     3.09 |   0.18 |  5.9 |     445.06 |   602.84
ccall                              (7) |    36.42 |  29.83 | 81.9 |     770.90 |   647.29
floatapprox                        (3) |     1.05 |   0.06 |  6.2 |     151.49 |   605.25
regex                              (3) |     0.45 |   0.03 |  6.4 |      59.50 |   605.38
float16                            (3) |     1.03 |   0.06 |  6.3 |     146.76 |   609.62
combinatorics                      (3) |     0.48 |   0.03 |  5.7 |      55.23 |   609.95
sysinfo                            (3) |     0.14 |   0.01 |  6.2 |      18.58 |   610.35
env                                (3) |     0.25 |   0.00 |  0.0 |      16.65 |   612.48
reflection                         (7) |     4.35 |   0.22 |  5.2 |     605.99 |   647.29
rounding                           (3) |     3.54 |   0.23 |  6.4 |     517.92 |   624.22
mod2pi                             (3) |     0.27 |   0.01 |  3.8 |      27.87 |   625.27
┌ Warning: File permissions tests skipped due to running tests as root (not recommended)
└ @ Main.Test15Main_read /usr/local/julia/share/julia/test/read.jl:468
┌ Warning: File permissions tests skipped due to running tests as root (not recommended)
└ @ Main.Test15Main_read /usr/local/julia/share/julia/test/read.jl:516
euler                              (3) |     0.77 |   0.06 |  7.8 |     132.19 |   635.13
read                               (5) |    22.54 |   1.16 |  5.2 |    2742.00 |  1274.61
errorshow                          (5) |     3.48 |   0.27 |  7.8 |     348.21 |  1274.61
sets                               (5) |     7.74 |   0.57 |  7.4 |     728.78 |  1274.61
goto                               (5) |     0.04 |   0.00 |  0.0 |       1.06 |  1274.61
llvmcall                           (5) |     0.20 |   0.00 |  0.0 |      18.58 |  1274.61
llvmcall2                          (5) |     0.03 |   0.00 |  0.0 |       1.92 |  1274.61
grisu                              (5) |     2.19 |   0.15 |  6.7 |     214.12 |  1274.61
broadcast                          (6) |    30.71 |   2.12 |  6.9 |    4708.71 |   606.00
some                               (5) |     0.76 |   0.08 | 10.5 |     108.20 |  1274.61
bitarray                           (2) |    96.79 |   5.24 |  5.4 |   13167.84 |   640.00
meta                               (6) |     0.76 |   0.05 |  6.7 |      97.42 |   608.39
stacktraces                        (5) |     1.41 |   0.13 |  9.1 |     177.53 |  1274.61
      From worker 5:	Warning: threaded loop executed in order
docs                               (2) |     3.08 |   0.22 |  7.1 |     398.29 |   661.18
show                               (3) |    22.38 |   1.44 |  6.4 |    2830.39 |   674.23
enums                              (2) |     3.23 |   0.31 |  9.7 |     400.73 |   668.11
threads                            (5) |     6.26 |   0.75 | 12.0 |     242.27 |  1274.61
subarray                           (4) |   156.17 |  11.21 |  7.2 |   25004.13 |   756.12
ranges                             (7) |    27.84 |   3.34 | 12.0 |    8859.54 |   647.29
checked                            (5) |     1.34 |   0.08 |  6.0 |      93.26 |  1274.61
bitset                             (4) |     1.30 |   0.08 |  5.9 |     114.49 |   757.50
int                                (2) |     2.74 |   0.07 |  2.7 |     134.53 |   680.61
cartesian                          (2) |     0.05 |   0.00 |  0.0 |       3.35 |   681.08
osutils                            (2) |     0.04 |   0.01 | 30.9 |       0.77 |   681.48
error                              (4) |     1.56 |   0.06 |  4.2 |      85.52 |   760.07
iostream                           (4) |     0.54 |   0.04 |  8.0 |      81.91 |   762.39
secretbuffer                       (4) |     0.65 |   0.27 | 41.7 |      41.75 |   762.53
specificity                        (4) |     0.18 |   0.01 |  7.0 |      19.74 |   762.53
boundscheck                        (5) |     3.72 |   0.02 |  0.4 |      19.59 |  1274.61
floatfuncs                         (7) |     4.34 |   0.33 |  7.7 |     617.05 |   647.29
      From worker 6:	Test Summary: | Pass  Total
      From worker 6:	@deprecate    |    6      6
      From worker 6:	Test Summary: | Pass  Total
      From worker 6:	firstcaller   |    1      1
      From worker 6:	Test Summary:              | Broken  Total
      From worker 6:	parser syntax deprecations |      1      1
syntax                             (5) |     1.77 |   0.10 |  5.8 |     129.46 |  1274.61
misc                               (6) |    14.79 |   1.46 |  9.9 |    1778.14 |   702.31
logging                            (7) |     4.25 |   0.27 |  6.3 |     504.54 |   647.29
reinterpretarray                   (4) |     5.78 |   0.52 |  9.1 |     745.91 |   808.71
missing                            (5) |     4.67 |   0.42 |  9.0 |     543.92 |  1274.61
channels                           (2) |    12.09 |   0.73 |  6.0 |     357.76 |   906.44
asyncmap                           (6) |     6.53 |   0.36 |  5.6 |     694.29 |   702.31
Pkg/resolve                        (2) |    18.20 |   2.47 | 13.6 |    6307.71 |   906.44
LinearAlgebra/qr                   (2) |    61.52 |   5.61 |  9.1 |   10391.26 |   947.27
SparseArrays/higherorderfns        (7) |    87.59 |   7.52 |  8.6 |   12318.83 |   830.36
cmdlineargs                        (3) |   116.05 |   0.09 |  0.1 |     167.70 |   686.55
SparseArrays/sparse                (4) |   123.92 |  32.88 | 26.5 |   10907.32 |  1045.26
LinearAlgebra/schur                (3) |    20.75 |   1.36 |  6.6 |    2165.09 |   722.59
LinearAlgebra/special              (4) |    14.24 |   1.20 |  8.4 |    1354.14 |  1062.80
SparseArrays/sparsevector          (5) |   137.64 |  10.89 |  7.9 |   18972.51 |  1309.27
LinearAlgebra/eigen                (3) |    24.48 |   2.17 |  8.9 |    3398.99 |   812.86
LinearAlgebra/lapack               (3) |    18.37 |   1.35 |  7.3 |    2454.81 |   865.68
LinearAlgebra/matmul               (7) |    82.30 |   7.71 |  9.4 |    9406.05 |  1008.25
LinearAlgebra/bunchkaufman         (4) |    30.89 |   3.66 | 11.9 |    4142.73 |  1129.15
LinearAlgebra/svd                  (5) |    33.23 |   3.19 |  9.6 |    4482.46 |  1325.44
LinearAlgebra/dense                (2) |   105.23 |  10.29 |  9.8 |   12886.50 |  1097.84
LinearAlgebra/tridiag              (3) |    22.80 |   1.91 |  8.4 |    2794.23 |   916.75
LinearAlgebra/bidiag               (7) |    44.17 |   4.46 | 10.1 |    5052.32 |  1095.54
LinearAlgebra/cholesky             (5) |    52.18 |   5.08 |  9.7 |    6297.39 |  1403.83
LinearAlgebra/generic              (7) |    12.04 |   1.29 | 10.7 |    1610.16 |  1189.95
LinearAlgebra/lu                   (2) |    40.39 |   4.18 | 10.3 |    4771.14 |  1264.09
LinearAlgebra/hessenberg           (2) |     0.85 |   0.07 |  8.6 |      85.39 |  1264.17
LinearAlgebra/uniformscaling       (5) |    11.65 |   1.06 |  9.1 |    1429.20 |  1466.13
LinearAlgebra/symmetric            (3) |    45.41 |   4.30 |  9.5 |    5325.17 |  1024.25
LinearAlgebra/blas                 (2) |    12.26 |   1.57 | 12.8 |    1528.43 |  1264.67
LinearAlgebra/pinv                 (3) |     5.92 |   0.73 | 12.3 |    1206.83 |  1126.88
LinearAlgebra/givens               (2) |     4.06 |   0.29 |  7.2 |     320.60 |  1266.17
LinearAlgebra/diagonal             (4) |    79.59 |  10.84 | 13.6 |    9992.08 |  1344.45
LinearAlgebra/adjtrans             (5) |    13.55 |   1.64 | 12.1 |    2001.57 |  1498.69
Dates/adjusters                    (5) |     2.30 |   0.21 |  9.2 |     267.72 |  1501.87
Dates/query                        (5) |     0.29 |   0.02 |  5.8 |      17.65 |  1502.28
LinearAlgebra/structuredbroadcast  (3) |    16.35 |   1.72 | 10.5 |    2253.19 |  1128.23
LinearAlgebra/lq                   (7) |    34.39 |   4.65 | 13.5 |    6276.17 |  1278.07
Dates/periods                      (5) |     8.95 |   0.81 |  9.1 |     995.87 |  1527.56
Dates/rounding                     (7) |     1.40 |   0.10 |  7.3 |     135.95 |  1279.88
Dates/types                        (5) |     0.66 |   0.03 |  5.3 |      52.04 |  1529.98
      From worker 2:	The following 'Resetting the helper list...' warning is expected:
┌ Warning: Resetting the helper list is currently unsupported:
│ ignoring all git credential helpers
└ @ LibGit2 /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/LibGit2/src/gitcredential.jl:234
Dates/arithmetic                   (5) |     4.88 |   0.68 | 14.0 |     653.68 |  1533.57
Dates/conversions                  (5) |     0.55 |   0.02 |  3.3 |      21.08 |  1533.57
Dates/ranges                       (3) |     9.60 |   0.85 |  8.9 |    1221.06 |  1129.46
Base64                             (5) |     1.22 |   0.15 | 12.7 |     189.59 |  1533.57
CRC32c                             (3) |     1.06 |   0.10 |  9.6 |     118.72 |  1129.90
Dates/io                           (7) |     9.53 |   0.83 |  8.7 |    1029.54 |  1287.86
DelimitedFiles                     (5) |     3.49 |   0.35 |  9.9 |     399.91 |  1539.16
Future                             (5) |     0.00 |   0.00 |  0.0 |       0.18 |  1539.16
InteractiveUtils                   (5) |     8.58 |   0.76 |  8.9 |     675.05 |  1604.83
Libdl                              (5) |     0.47 |   0.04 |  7.6 |      36.79 |  1609.26
Logging                            (5) |     2.45 |   0.31 | 12.8 |     361.65 |  1609.80
Markdown                           (5) |     4.26 |   0.40 |  9.4 |     474.79 |  1617.30
Dates/accessors                    (4) |    48.22 |   3.07 |  6.4 |    3771.09 |  1344.45
Mmap                               (5) |     8.68 |   6.74 | 77.7 |     256.59 |  1619.98
Profile                            (5) |     5.70 |   0.28 |  4.9 |     294.08 |  1661.16
FileWatching                       (7) |    36.74 |   2.69 |  7.3 |     218.86 |  1291.06
Printf                             (4) |    11.92 |   1.14 |  9.5 |    1276.24 |  1351.54
┌ Warning: TerminalMenus: Unable to enter raw mode: Base.IOError("stream is closed or unusable", 0)
└ @ REPL.TerminalMenus /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/REPL/src/TerminalMenus/util.jl:21
      From worker 5:	
┌ Warning: TerminalMenus: Unable to enter raw mode: Base.IOError("stream is closed or unusable", 0)
└ @ REPL.TerminalMenus /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/REPL/src/TerminalMenus/util.jl:21
      From worker 5:	
REPL                               (5) |    20.74 |   2.22 | 10.7 |    2302.38 |  1735.83
Serialization                      (5) |     5.30 |   0.92 | 17.4 |     824.96 |  1738.39
Sockets                            (5) |     2.46 |   0.17 |  6.8 |     173.07 |  1738.39
Random                             (7) |    28.03 |   2.40 |  8.6 |    2768.23 |  1394.07
LinearAlgebra/triangular           (6) |   333.40 |  29.13 |  8.7 |   39220.42 |  1472.42
LibGit2/libgit2                    (2) |    92.29 |   1.69 |  1.8 |    1365.68 |  1498.90
UUIDs                              (2) |     0.29 |   0.03 |  8.8 |      21.61 |  1498.90
Unicode                            (2) |     3.38 |   0.35 | 10.3 |     379.02 |  1501.12
Statistics                         (5) |    20.20 |   2.35 | 11.6 |    2341.13 |  1782.34
┌ Warning: Omitting `@test_deprecated` tests which can't yet
│ be tested in --depwarn=error mode
└ @ Main.Test52Main_Test /usr/local/julia/share/julia/stdlib/v1.1/Test/test/runtests.jl:736
Test                               (6) |    20.68 |   0.44 |  2.1 |     473.28 |  1510.78
Distributed                        (3) |    91.40 |   0.02 |  0.0 |      11.81 |  1129.99
SHA                                (4) |    53.68 |   0.77 |  1.4 |     828.02 |  1399.55
SuiteSparse                        (7) |    33.53 |   3.74 | 11.1 |    3606.77 |  1459.67

Executing tests that run on node 1 only:
precompile                         (1) |    16.61 |   0.10 |  0.6 |     414.15 |   257.89
SharedArrays                       (1) |    14.04 |   0.61 |  4.4 |    1802.37 |   288.03
stress                             (1) |    37.59 |   0.39 |  1.0 |     798.04 |  1282.07

Test Summary: |     Pass  Broken     Total
  Overall     | 37535772  327826  37863598
    SUCCESS
```

**Comment by ViralBShah** [comment]
@tianon Are there detailed download stats available for the Julia docker image? If you are one of the maintainers of the docker julia images, is it possible to give me access - viralbshah? Thank you.

**Comment by tianon** [comment]
Unfortunately we don't get access to anything like that. 😞

The best I can suggest is trying to contact Docker support, they might be
able to offer more.

**Comment by ViralBShah** [comment]
Thank you. I thought it was worth asking. Does it show anything better than 1M+ to you? Something we can record as we go along to build our own history?

**Comment by tianon** [comment]
Yeah! There's an undocumented API (so might be subject to change without
notice): https://hub.docker.com/v2/repositories/library/julia/

See also https://github.com/infinityworks/docker-hub-exporter (which
consumes that API to provide Prometheus compatible versions of those
metrics).

**Comment by ViralBShah** [comment]
Thank you. The API says `"pull_count": 4312707`. Do you know how to interpret this number?

**Comment by tianon** [comment]
Pretty sure that corresponds to any time someone does a `docker pull julia:xxx` (or indirectly does so via `docker build --pull`, etc).

(Very similar to old web counters :+1:)

**Pull request merged**
