### PR TITLE
Bump stable release to 1.4.1

### PR DESCRIPTION
**Pull request by ararslan**
There are no ARMv7 binaries for 1.4.1.

### CODE REVIEW

**Comment by ViralBShah** [comment]
@staticfloat When might we get the armv7 binaries? If they are being built, it may be ok to hold to have everything.

**Comment by ararslan** [comment]
I attempted to build them but wasn't able to get a buildbot build through. It seems no recent ARMv7 binaries have made it through at all. I thought the point of bumping the tier back to 3 for ARMv7 was that we wouldn't hold releases based on the availability of binaries, since we typically don't expect them to exist.

**Comment by ViralBShah** [comment]
Ok. But how did we get the 1.4 binaries?

**Comment by ararslan** [comment]
Elliot magic

**Comment by staticfloat** [comment]
We bumped some deps between 1.4.0 and 1.4.1 that don't have quite the right names for 1.4.  I've duplicated some names, so now we've got a build going through here: https://build.julialang.org/#/builders/5/builds/10723

**Comment by ararslan** [comment]
Looks like the build failed. :/

**Comment by staticfloat** [comment]
I fixed it: https://s3.amazonaws.com/julialangnightlies/pretesting/linux/armv7l/1.4/julia-381693d3df-linuxarmv7l.tar.gz

**Comment by ararslan** [comment]
Everything is now in place and the checksums have been updated.

**Comment by ViralBShah** [comment]
Love the PR! So much better than it used to be! Thanks @tlienart

**Pull request merged**
