### PR TITLE
make font color of .main-heading black

### PR DESCRIPTION
**Pull request by kolokd**
white text on a light background makes the text unreadable. as the other text on the page has black font color on white background, making this also black increase consistency.

### CODE REVIEW

**Comment by tlienart** [comment]
could you post a before/after screenshot?

**Comment by kolokd** [comment]
oh, my bad. i have set ublock to Block media elements larger than 30 KB. When the page loads because of the background image is 55.3 KB it blocked form loading. so i didn't see the background.

**Comment by kolokd** [comment]
i think the background image should be optimized.

**Comment by tlienart** [comment]
yes definitely, see also #791 (I wholly agree that images should be small, ideally SVG < 100kb; your limit is probably a bit harsh in that respect).

**Comment by kolokd** [comment]
yes, it is harsh. but i have to pay for every bytes.

**Pull request closed without merging**
