### PR TITLE
Remove unavailable video

### PR DESCRIPTION
**Pull request by giordano**
The [Intro to Julia Data Frames](https://www.youtube.com/watch?v=0-Xsts_s5W) is unavailable for me, is it only me? CC: @bkamins

### CODE REVIEW

**Comment by logankilpatrick** [comment]
Link does not work for me either. However, there’s an updated tutorial on YouTube right now.

**Comment by ViralBShah** [comment]
We probably should only advertise JuliaAcademy, and standardize around that.

**Comment by logankilpatrick** [comment]
Yeah, I’ll fix that up when I re-do the learning page.

**Comment by bkamins** [comment]
This is the best approach. I do not know what was the link (I do not recall providing it). Anyway it was for sure an outdated video. JuliaAcademy is I guess a good reference as it is curated (and I can update materials after each major release there). So probably it is best not to give links to YouTube at all but to pages that are guaranteed to have correct links?

**Comment by ViralBShah** [comment]
Yes. People will still find the videos on youtube. But we should advertise the academy. Probably in the video descriptions on youtube, we can say they are part of a series on JuliaAcademy.

BTW, we should also include that information on DataFrames.jl (in the README and docs) as a pointer.

**Comment by bkamins** [comment]
> BTW, we should also include that information on DataFrames.jl (in the README and docs) as a pointer.

@logankilpatrick - can you please make a PR there the way you feel appropriate?

**Comment by logankilpatrick** [comment]
Yes!

**Comment by logankilpatrick** [comment]
PR is open!

**Pull request merged**
