### PR TITLE
Create "Other Tools" section on the Main JuliaLang home screen 

### LINKED ISSUE #449: Debugger and Profiler
Mention them prominently on the landing page.

### PR DESCRIPTION
**Pull request by logankilpatrick**
Closes #449 

WIP Do Not Merge.

### CODE REVIEW

**Comment by logankilpatrick** [comment]
TODO: waiting on Julia Debug logo and I am having a Julia Profile Module logo made.

**Comment by logankilpatrick** [comment]
Screen Shot 2019-12-21 at 8 05 09 AM

Obviously need to fix some formatting and such still, but is the basic idea along the lines of what you imagined @ViralBShah

**Comment by ViralBShah** [comment]
Make it Essential Packages?

**Comment by logankilpatrick** [comment]
I’m okay with that, but seems like a weird way to phrase it. Wouldn’t everything in Julia Base be considered essential otherwise it would be in a stand alone repo?

**Comment by ViralBShah** [comment]
Julia Base if anything is moving towards being minimal. I feel it is a strength of Julia that these things can be standalone.

BTW, where do we showcase the GPU compliation? Perhaps in this section?

**Comment by logankilpatrick** [comment]
Tested locally and it looks good!

**Comment by timholy** [comment]
The "other tools" section doesn't show up for me.

**Comment by logankilpatrick** [comment]
Temporarily removed it while I finalize the formatting and such.

**Pull request merged**
