### PR TITLE
Cleaner downloads table

### PR DESCRIPTION
**Pull request by IanButterworth**
Just an idea. Treats it more like a table, removes repetition.

The other tables need updating if approved of

This PR

Screen Shot 2022-10-30 at 12 05 08 PM

vs main

Screen Shot 2022-10-30 at 12 05 59 PM

### CODE REVIEW

**Comment by IanButterworth** [comment]
Not sure what's going on with CI but this is a local render

Screen Shot 2022-10-30 at 12 05 08 PM

vs main

Screen Shot 2022-10-30 at 12 05 59 PM

**Review by DilumAluthge — APPROVED** [review]
I think we should preserve the text `aarch64` (for Linux ARM 64-bit), but otherwise LGTM.

**Comment by logankilpatrick** [comment]
@IanButterworth this looks good to me, I am happy to proceed with a merge if you think it's good to go.

**Comment by IanButterworth** [comment]
The other tables need updating before merge.

**Comment by logankilpatrick** [comment]
One piece of feedback, maybe we can add a sentence somewhere that says what "archive" means in this context, I genuinely don't know what it is.

**Comment by logankilpatrick** [comment]
Are you willing/able to do that as well? If not, I can take a stab this week sometime.

**Comment by logankilpatrick** [comment]
@IanButterworth Are we good to merge this?

**Comment by IanButterworth** [comment]
> The other tables need updating before merge.

Please feel free to do this and push here. I think they should all match in format.

**Comment by ViralBShah** [comment]
I agree we should not use the word `archive`. Most people don't know what it means.

**Comment by logankilpatrick** [comment]
I can take this PR over the finish line, but what do we want "Archive" to say? It is unclear to me what that means here.

**Comment by ViralBShah** [comment]
I suggest just updating this and we can wordsmith later.

**Pull request closed without merging**
