### PR TITLE
Update download links to v1.4.0

### PR DESCRIPTION
**Pull request by ararslan**
Also move v1.3.1 to the old releases page and update the homepage download button to say 1.4.

### CODE REVIEW

**Comment by ViralBShah** [comment]
@logankilpatrick can we delete all these failing CI things?

**Comment by logankilpatrick** [comment]
It should be all set now

**Comment by ViralBShah** [comment]
@tlienart Is there a way in Franklin to set some values - like lts_release, stable_release, etc. so that we don't have to edit these things manually in each release and they are uniformly updated across the website?

**Comment by tlienart** [comment]
Yes, basically just define variables in the `config.md`, these can then be used in HTML using `{{fill varname}}`

If someone gives me more detailed specs of what/where this is desired, I’m happy to put this in place

**Comment by ViralBShah** [comment]
> Yes, basically just define variables in the `config.md`, these can then be used in HTML using `{{fill varname}}`
> 
> If someone gives me more detailed specs of what/where this is desired, I’m happy to put this in place

@tlienart Filed #677 for further discussions

**Pull request merged**
