### PR TITLE
delete JuliaQuantum

### PR DESCRIPTION
**Pull request by Roger-luo**
discussed in https://discourse.julialang.org/t/new-website/12844/61?u=roger-luo

And issued here: https://github.com/JuliaQuantum/JuliaQuantum.github.io/issues/47

I guess we might just delete it and move those old packages to JuliaArchive.

### CODE REVIEW

**Comment by Roger-luo** [comment]
Closed due to @i2000s 's review

**Comment by i2000s** [comment]
Again, I would suggest to be more patient to see the updates.

**Comment by ViralBShah** [comment]
So, what should be done here?

**Comment by i2000s** [comment]
@ViralBShah I, as one of the co-founders of the JuliaQuantum, personally suggest leaving the list as was. JuliaQuantum as an open community for promoting Julia in the quantum community has been working as hard as we can in the past and is still working on updating the org's policy, plans and repos under open discussions to serve the community in a better way. If there is any dispute, the OP should give a detailed reasoning so that I can respond after my academic traveling (ending next week). Thank you for your understanding.

**Comment by ViralBShah** [comment]
Thank you. I am closing this for now. I don't think we need to delete things, and ideally look for people to contribute to and co-own organizations. Can always revisit in the future.

**Comment by ThoAppelsin** [comment]
I am looking at this a year after the discussions. I haven't noticed any progress on the JuliaQuantum organization.

**Pull request merged**
