### PR TITLE
Align navbar items better

### PR DESCRIPTION
**Pull request by zdroid**
Before:
Screenshot from 2020-05-14 14-44-27

After:
Screenshot from 2020-05-14 14-56-30

### CODE REVIEW

**Comment by tlienart** [comment]
nice! how about padding a little bit left and right so  that julia logo / sponsor are not directly against the boundary?

**Comment by zdroid** [comment]
The inner or the outer (navbar's) boundary?

**Comment by zdroid** [comment]
Also the problem with using 1/9th size is that isn't scalable (in case more items are added). It also isn't guaranted to work due to different text lengths of nav items.

**Comment by tlienart** [comment]
fair enough for the 1/9; looking at your second screenshot there's just more whitespace between the logo and download, it might look more balanced if some of that whitespace was left of the logo (resp. right for sponsor). 
I'm not desperate for that change if you don't think it makes things more balanced then ignore and we can just merge this

**Comment by zdroid** [comment]
You were right, looks better now. I also styled the logo to style better vertically.
Screenshot from 2020-05-14 18-02-59

**Comment by tlienart** [comment]
Awesome thanks, let's merge this it seems like a net improvement and we can always get back to it if needed

**Pull request merged**
