### PR TITLE
Add Calendar to the community section 

### PR DESCRIPTION
**Pull request by logankilpatrick**
Hey @tlienart, is it possible to imbed this iframe into the markdown?

### CODE REVIEW

**Comment by ViralBShah** [comment]
Can I see this calendar on the web itself, or do I need to add it to my google calendar?

**Comment by logankilpatrick** [comment]
Yes, if we embed it, you should be able to see it without signing in or anything, but I need to figure out how to embed it since we are using Markdown and not HTML.

**Comment by tlienart** [comment]
Here: https://julialang.netlify.com/community/

**Comment by ViralBShah** [comment]
@logankilpatrick Shows an empty calendar right now. We should populate the calendar before merging this PR.

**Comment by abhishalya** [comment]
It doesn't scale properly on mobile devices. So maybe we should fix that too.

**Comment by logankilpatrick** [comment]
@abhishalya we need some additional code in JS or something like that since by default iframe HTML tags have a specific length and width in pixels that will not auto change based on the platform.

**Comment by logankilpatrick** [comment]
@ViralBShah what other events should be added to the calendar? I added the AMA for Thursday.

**Comment by ViralBShah** [comment]
Shall we add some ofthe events of the past week? What about all those twitch livestreams?

**Comment by logankilpatrick** [comment]
@ViralBShah I added the virtual meetup form last week. Once this goes live, if the folks who did those streams want to go back in and add past streams they will be able to.

**Comment by logankilpatrick** [comment]
I am ready to merge this if you all are

**Pull request merged**
