### PR TITLE
[GSOC] add GraphNeuralNetworks.jl

### PR DESCRIPTION
**Pull request by CarloLucibello**
I'm not sure if I should put this as a separate entry (as I did) or on Flux's page.
cc @Wimmerer

Flux's page is a bit rotten and bloated, we should polish it. Maybe @logankilpatrick and @darsnack are already onto it?

### CODE REVIEW

**Comment by logankilpatrick** [comment]
I have no preference for which page gets updated. It's up to @DhairyaLGandhi

**Comment by DhairyaLGandhi** [comment]
It can go on the Flux page.

**Comment by logankilpatrick** [comment]
@DhairyaLGandhi Can you clean up the page to make note of this and send people over to the Flux page?

**Comment by ViralBShah** [comment]
I'm merging this for now. Better to have it and refactor later, than not.

**Comment by CarloLucibello** [comment]
Thanks!

**Pull request merged**
