### PR TITLE
Add single page for all GSoC projects to improve searchability

### PR DESCRIPTION
**Pull request by logankilpatrick**

### CODE REVIEW

**Comment by logankilpatrick** [comment]
Closes #1231

**Comment by logankilpatrick** [comment]
Figured this out by reading: https://franklinjl.org/syntax/markdown/#inserting_markdown

**Comment by logankilpatrick** [comment]
@tlienart Hey, any idea what I am doing wrong here: https://julialang.netlify.app/previews/pr1261/jsoc/allprojects/ I am trying to include all of the pages into a single one for discoverability

**Comment by tlienart** [comment]
I'll look into it over the weekend

**Comment by tlienart** [comment]
see #1266

**Pull request closed without merging**
