### PR TITLE
Refactor JuliaCon video styles

### PR DESCRIPTION
**Pull request by zdroid**
Addresses "make the youtube video link smaller (see GO front page)" from #800 and cleans the CSS up.

Screenshot from 2020-05-29 16-20-08
->
Screenshot from 2020-05-29 16-19-57

### CODE REVIEW

**Comment by ViralBShah** [comment]
Looks good.

**Comment by ViralBShah** [comment]
Is this still going to pick a random video from that list and show?

**Comment by abhishalya** [comment]
No, this does not work properly on mobile devices.

**Comment by ViralBShah** [comment]
@zdroid Perhaps revert or fix?

**Comment by zdroid** [comment]
A fix is incoming.

**Pull request merged**
