### PR TITLE
Fix broken github links

### PR DESCRIPTION
**Pull request by nodivbyzero**
Links to `Help Wanted Issues` and `Good First Issue` on Home page were broken.
This PR fixes those links.

### CODE REVIEW

**Comment by fredrikekre** [comment]
The existing links work for me.

**Comment by nodivbyzero** [comment]
@fredrikekre Can you try to open them in Incognito mode?

**Comment by logankilpatrick** [comment]
I believe you have to be signed into GitHub for them to work if I recall correctly

**Comment by fredrikekre** [comment]
Ah, maybe <https://github.com/search?q=is%3Aopen+is%3Aissue+language%3AJulia+label%3A%22help+wanted%22> works regardless of whether you are logged in?

**Comment by logankilpatrick** [comment]
Closing for now since those links exist specifically to be broader than the issues just in core julia. If you think there's something we can do to remind folks they need to sign in, let me know!

**Comment by logankilpatrick** [comment]
Updated to the version @fredrikekre sent above, thank you both!

**Pull request merged**
