### PR TITLE
Update FastAI.jl GSoC

### PR DESCRIPTION
**Pull request by darsnack**
Updates FastAI.jl GSoC project in response to #1139. My only concern with this project is timeline (i.e. will we have enough work for the student when summer rolls around). Previously we were focused on the fast.ai book, so if we can get Jeremy's permission (it's copyrighted) then recreating the book would become part of the scope. In which case, I no longer have timeline concerns cause there will be plenty of work.

cc @lorenzoh

### CODE REVIEW

**Review by logankilpatrick — APPROVED** [review]

**Comment by darsnack** [comment]
I just want @lorenzoh's feedback before we merge

**Review by darsnack — COMMENTED** [review]
This is good to go on our end

**Comment by logankilpatrick** [comment]
Thank you all!

**Comment by lorenzoh** [comment]
Thanks @darsnack!

**Pull request merged**
