### PR TITLE
Julia: A fresh approach to computing

### PR DESCRIPTION
**Pull request by tisztamo**
Removing a single word to completely change the first impression of the landing user.

Based on https://discourse.julialang.org/t/future-directions-of-julia/46269/30

### CODE REVIEW

**Comment by ViralBShah** [comment]
We've avoided doing that because it is a bit misleading. Happy to leave it open to reconsider.

@JeffBezanson @StefanKarpinski Any thoughts?

**Comment by StefanKarpinski** [comment]
Not sure. Let's see what @JeffBezanson thinks. If we're going to change this, I wonder if a different slogan altogether would be better.

**Comment by fredrikekre** [comment]
Could also just remove it? This is the only place where this slogan is still used still AFAIK. It is removed from the startup banner for example.

**Comment by ViralBShah** [comment]
Could go fully minimal and just say "Julia"

**Comment by StefanKarpinski** [comment]
Yeah, that seems good. No need for a slogan anymore really.

**Comment by JeffBezanson** [comment]
I agree we can just remove the slogan. Then we could also make the top banner use a bit less vertical space; it seems very large to me for something that has little content.

**Pull request closed without merging**
