### PR TITLE
GSoC: Pluto: add electron project

### PR DESCRIPTION
**Pull request by fonsp**
Another awesome GSoC project to bring the Julia ecosystem forward!

(Still WIP, @ctrekker will write the rest of the proposal later tonight (US time))

### CODE REVIEW

**Comment by logankilpatrick** [comment]
@fonsp please add if these are 175 or 350 hour projects

**Comment by fonsp** [comment]
@ctrekker I'd say 175?

**Comment by ctrekker** [comment]
@fonsp Yeah I'd say all of them are 175 hours

**Comment by logankilpatrick** [comment]
Are we good to merge this?

**Comment by ctrekker** [comment]
Yes we are good to merge

**Comment by logankilpatrick** [comment]
Thank you both!

**Pull request merged**
