### PR TITLE
[WIP] Switch site to hugo

### PR DESCRIPTION
**Pull request by abhishalya**
**Important: Review extensively**

Coming from https://github.com/JuliaLang/hugo.julialang.org its time to do final reviews before officially switching. This is a long PR and it is very important to review everything before this PR is merged.

I'll be making changes periodically and please **do not merge** until the `[WIP]` is removed from the title of this PR.

Closes https://github.com/JuliaLang/www.julialang.org/issues/531

### CODE REVIEW

**Comment by cormullion** [comment]
I've reported a few issues here: https://github.com/JuliaLang/hugo.julialang.org/issues/15

**Comment by logankilpatrick** [comment]
Hey @abhishalya in the future, make these sorts of changes on a branch on the main repo vs your fork. I am trying to resolve the merge conflicts but not sure how to given that the main branch of your forked repo is not at the same place as the main branch on this repo. 

Any thoughts to resolve the conflict @ViralBShah

**Comment by abhishalya** [comment]
Working on this now

**Comment by ViralBShah** [comment]
Linking @cormullion's  comments here. Looks like we are close. I suggest we try to get this merged soon.

https://github.com/JuliaLang/hugo.julialang.org/issues/15

**Comment by ViralBShah** [comment]
I wouldn't worry about the syntax coloring ones.

**Pull request merged**
