### PR TITLE
Over 3000 packages!

### PR DESCRIPTION
**Pull request by PallHaraldsson**
[skip ci]

### CODE REVIEW

**Comment by PallHaraldsson** [comment]
By my county there are now 2993 (plus jll packages), but with 15 new packages in the pipeline waiting to be registered, many from today! So, wait with merging a bit, should it take long?

Congratulation.

I have a feeling 13 millions downloads might also be outdated....

**Comment by tlienart** [comment]
thanks

**Comment by ViralBShah** [comment]
I think you can just count the number of directories in the general registry

**Comment by ViralBShah** [comment]
Let's not update number of downloads. I think over 10 million downloads is what we should use going forward.

**Pull request merged**
