### PR TITLE
Footer: Add a link to `status.julialang.org`

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by logankilpatrick** [comment]
The status page is awesome!

**Comment by DilumAluthge** [comment]
Yeah @fredrikekre and @staticfloat did good work.

**Comment by staticfloat** [comment]
It's all @fredrikekre, I just set things up once he'd already gone through the work of figuring out what we want.

**Comment by DilumAluthge** [comment]
Anyway, anyone object to adding this link to the footer?

I put it under "About", but we can put it under a different heading if people prefer.

**Comment by ViralBShah** [comment]
How about in Downloads? Maybe call it `PkgServer Status` or `Pkg status` is that is too long?

**Comment by DilumAluthge** [comment]
Sure! Take a look.

**Pull request merged**
