### PR TITLE
[WIP] Julia Summer of Code blog post

### PR DESCRIPTION
**Pull request by logankilpatrick**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Maybe have the students link their blog posts in here?

**Comment by logankilpatrick** [comment]
Yeah, I have them all saved, just have not copied them all over yet.

**Comment by ViralBShah** [comment]
Let's get this out in the next few days?

**Comment by logankilpatrick** [comment]
This will be released to coincide with the last day of GSoC (September 8th).

**Comment by frankschae** [comment]
Hi! Here are my posts:

https://frankschae.github.io/post/gsoc2020-high-weak-order-solvers-sde-adjoints/
https://frankschae.github.io/post/high-weak/

**Comment by abhinavmehndiratta** [comment]
Here are my blog posts -

https://abhinavmehndiratta.github.io/2020-06-02/parallel-connected-components
https://abhinavmehndiratta.github.io/2020-06-11/parallel-scc
https://abhinavmehndiratta.github.io/2020-07-28/multithreaded-triangle-count

**Comment by tejasvaidhyadev** [comment]
Here are my blogs-
- https://tejasvaidhyadev.github.io/blog/First-Milestone
- https://tejasvaidhyadev.github.io/blog/Sentencepiece
- https://tejasvaidhyadev.github.io/blog/Hey-Albert

I am working on one more technical blog

**Comment by SebastianGuadalupe** [comment]
Hi there! here is a link to my blog posts:
https://nextjournal.com/sguadalupe

**Comment by Sov-trotter** [comment]
Hi there! All my blogs will appear here. WIP for now. :)
https://sov-trotter.github.io/blog/

**Comment by Sov-trotter** [comment]
Hi there! All my blogs will appear here. WIP for now. :)
https://sov-trotter.github.io/blog/

**Comment by archit120** [comment]
My WIP post - https://archit.me/blog/gsocfinal

**Comment by MartinuzziFrancesco** [comment]
Hi! These are my posts:

- https://martinuzzifrancesco.github.io/posts/01_gsoc_week/
https://martinuzzifrancesco.github.io/posts/01_gsoc_week/
https://martinuzzifrancesco.github.io/posts/01_gsoc_week/
https://martinuzzifrancesco.github.io/posts/01_gsoc_week/
https://martinuzzifrancesco.github.io/posts/01_gsoc_week/
https://martinuzzifrancesco.github.io/posts/01_gsoc_week/
https://martinuzzifrancesco.github.io/posts/01_gsoc_week/
https://martinuzzifrancesco.github.io/posts/01_gsoc_week/
https://martinuzzifrancesco.github.io/posts/01_gsoc_week/

**Comment by MartinuzziFrancesco** [comment]
HI! These are my blog posts:

- https://martinuzzifrancesco.github.io/posts/01_gsoc_week/
 -https://martinuzzifrancesco.github.io/posts/02_gsoc_week/
- https://martinuzzifrancesco.github.io/posts/03_gsoc_week/
- https://martinuzzifrancesco.github.io/posts/04_gsoc_week/
- https://martinuzzifrancesco.github.io/posts/05_gsoc_week/
- https://martinuzzifrancesco.github.io/posts/06_gsoc_week/
- https://martinuzzifrancesco.github.io/posts/07_gsoc_week/
- https://martinuzzifrancesco.github.io/posts/08_gsoc_week/
- https://martinuzzifrancesco.github.io/posts/09_gsoc_week/
- https://martinuzzifrancesco.github.io/posts/10_gsoc_week/
- https://martinuzzifrancesco.github.io/posts/11_gsoc_week/
- https://martinuzzifrancesco.github.io/posts/12_gsoc_week/

**Comment by nirmal-suthar** [comment]
Hii here is the link to my blog posts
https://nextjournal.com/nirmal-suthar/

**Comment by utkarsh530** [comment]
Hello,
These are my links to all the blog posts:
- https://utkarsh530.github.io/blog/post/gsoc-blog-final/
- https://utkarsh530.github.io/blog/post/gsoc-blog-3/
- https://utkarsh530.github.io/blog/post/gsoc-blog-2/
- https://utkarsh530.github.io/blog/post/gsoc-blog-1/

**Comment by SaranjeetKaur** [comment]
Hi there! Here are links to my blog posts:

* https://nextjournal.com/Saranjeet-Kaur/extending-nestedsamplersjl
* https://nextjournal.com/Saranjeet-Kaur/illustrations-of-use-of-nestedsamplersjl

More blogs are being worked on and are yet to appear here!

**Comment by ashryaagr** [comment]
Hi,
My blog post: https://nextjournal.com/ashryaagr/fairness

**Comment by krish8484** [comment]
Hi,
I have updated this one blog throughout the summer
https://nextjournal.com/krish8484/a-standards-compliant-interval-arithmetic-library

**Comment by KirillZubov** [comment]
HI, these are my blog posts:
https://nextjournal.com/kirill_zubov/physics-informed-neural-networks-pinns-solvers-on-julia-gsoc-2020-first-evaluations
https://nextjournal.com/kirill_zubov/physics-informed-neural-networks-pinns-solver-on-julia-gsoc-2020-second-evaluation
https://nextjournal.com/kirill_zubov/physics-informed-neural-networks-pinns-solver-on-julia-gsoc-2020-final-report

**Comment by ashutosh-b-b** [comment]
Hi! Here's mine 
[https://nextjournal.com/ashutosh-b-b/jsoc-2020-working-with-differential-equations-and-neural-networks](https://nextjournal.com/ashutosh-b-b/jsoc-2020-working-with-differential-equations-and-neural-networks)

**Comment by eulerkochy** [comment]
Hi!
I've published these two blogs.
https://nextjournal.com/eulerkochy/ordered-dictionary-an-alternative-approach
https://nextjournal.com/eulerkochy/gsoc-20-in-datastructures.jl

**Comment by SebastianM-C** [comment]
Here is my post
https://nextjournal.com/SebastianM-C/a-fresh-approach-to-n-body-problems

**Comment by UzielLinares** [comment]
Hi, 

These are my blog posts:
https://nextjournal.com/UzielLinares/bounders-for-taylormodels
https://nextjournal.com/UzielLinares/rigorous-interval-optimization-with-taylor-models
https://nextjournal.com/UzielLinares/validated-integration-of-ordinary-differential-equations

**Comment by ludoro** [comment]
These are my articles:
https://nextjournal.com/ludoro/from-jsoc-to-gsoc-a-new-beginning-with-surrogatesjl
https://nextjournal.com/ludoro/july-deliverables-two-new-surrogates-methods-and-benchmarking
https://nextjournal.com/ludoro/closing-the-gsoc-adding-a-new-optimization-nd-optimization-method-finishing-benchmarks-and-fixing-minor-bugs

**Comment by chengchingwen** [comment]
Hi! Here link to my blog posts:
https://nextjournal.com/chengchingwen

**Review by ChrisRackauckas — APPROVED** [review]
Others can be added later too, but lets at least get this out there.

**Pull request merged**
