### PR TITLE
Fix yotube and twitter icons svg in

### PR DESCRIPTION
**Pull request by howdyAnkit**
the twitter and youtube icons seem to be broken

### CODE REVIEW

**Comment by ViralBShah** [comment]
@zdroid Is this good?

**Comment by tlienart** [comment]
What was broken? And these files should go through svgo

**Comment by howdyAnkit** [comment]
julia

I just checked in both windows and Linux devices in chrome browser the images for the youtube and twitter seem not to be present? but however, the SVG images of youtube and twitter are present on the android devices of chrome browser. PFA image for reference

**Comment by tlienart** [comment]
Weird, thanks for reporting.

Would you mind please optimising the SVG code you posted using `svgo`, verifying that you can serve the site locally and show it on chrome browser as you tried?

Thanks

**Comment by howdyAnkit** [comment]
@zdroid thanks for pointing it out. it seems one of my ad-blocker chrome-extension was preventing the svg images.
ad-blocker

**Comment by zdroid** [comment]
@howdyAnkit Good to hear that! You can always replace it with another AdBlock extension, there are too many of those. :smile:

**Pull request closed without merging**
