### PR TITLE
Update in Getting-started in Julia

### PR DESCRIPTION
**Pull request by ashwani-rathee**
In reference to #967 "Major Update Needed in Getting Started with Julia" page

### CODE REVIEW

**Comment by logankilpatrick** [comment]
@ashwani-rathee Please give this another look to fix grammar and spelling issues.

**Comment by ashwani-rathee** [comment]
@logankilpatrick any update or any review on this??

**Comment by logankilpatrick** [comment]
Will review it this week. 

Best, 
Logan Kilpatrick

**Comment by ViralBShah** [comment]
Hi @ashwani-rathee. Appreciate the contribution, but these edits are not grammatically right. Hence, I am closing this PR.

**Comment by ashwani-rathee** [comment]
Okay

**Pull request closed without merging**
