### PR TITLE
Add redirects for nightlies.html and ideas-page.html

### PR DESCRIPTION
**Pull request by abhishalya**
Also adds changes for the deployment.

- [ ] Add `ACTIONS_DEPLOY_KEY` to secrets.

Closes https://github.com/JuliaLang/www.julialang.org/issues/579, https://github.com/JuliaLang/www.julialang.org/issues/584

### CODE REVIEW

**Comment by abhishalya** [comment]
I've tested this on my forks gh-pages branch. You can check it out at [codemute.ml](https://codemute.ml).

**Comment by logankilpatrick** [comment]
https://julialang.org/downloads/nightlies.html still 404’s for me

**Comment by abhishalya** [comment]
@ViralBShah @logankilpatrick Can you guys add ACTIONS_DEPLOY_KEY to secrets. The deployment method is changed here.

**Comment by logankilpatrick** [comment]
Pm me the secrets value on slack and I’ll add it

**Comment by abhishalya** [comment]
The changes are deployed now, so it should all work now.

**Pull request merged**
