### PR TITLE
Fix 662

### LINKED ISSUE #662: "Talk to us" icons not showing
The icons for github etc. in "Talk to Us" are not showing.

### PR DESCRIPTION
**Pull request by tlienart**
this adds (back?) logos for Discourse, GitHub, Twitter and YouTube in the "talk to us" section (closes #662). And fixes the Jupyter logo.

@abhishalya  I'm not satisfied with the  horizontal alignment of those blocks but I don't know this bootstrap business well enough to get what I want; would you mind taking a look? thanks!

### CODE REVIEW

**Comment by tlienart** [comment]
Ok I fixed the alignment issue

**Comment by ViralBShah** [comment]
Nice!

**Comment by ViralBShah** [comment]
Would it be easy to put all 4 of them in one row?

**Comment by tlienart** [comment]
ah yes! will try that

**Comment by tlienart** [comment]
done

**Comment by ViralBShah** [comment]
Thank you!

**Pull request merged**
