### PR TITLE
Set stable version to 1.8.3

### PR DESCRIPTION
**Pull request by Nyoho**
I would like to download 1.8.3 from the download page https://julialang.org/downloads/

### CODE REVIEW

**Comment by Nyoho** [comment]
In spite of using `oldreleases.jl`, many lines in oldrelease.md were somehow updated.

**Review by DilumAluthge — CHANGES_REQUESTED** [review]
Just FYI, Julia 1.8.3 has not actually been released yet. We'll post an announcement on Discourse when the release has officially been made.

**Comment by Nyoho** [comment]
I see. Does it mean that this release https://github.com/JuliaLang/julia/releases/tag/v1.8.3 is not the official release? Anyway, I'll wait the post of Discourse. Thank you.

**Comment by KristofferC** [comment]
>  Does it mean that this release https://github.com/JuliaLang/julia/releases/tag/v1.8.3 is not the official release?

It is the tag for the official release but there is some time between that and binaries getting created and put in their correct place etc.

**Comment by Nyoho** [comment]
I completely understood! Thank you for explanation.

**Pull request closed without merging**
