### PR TITLE
Add a floating link to edit the source of pages

### PR DESCRIPTION
**Pull request by tlienart**
Suggested by @fredrikekre in #787 

~~**Now**~~ (see screenshot further below, floating link)

The first link (on GitHub) links to the source of the page for instance:

* front page => https://github.com/JuliaLang/www.julialang.org/blob/master/index.html
* learning page => https://github.com/JuliaLang/www.julialang.org/blob/master/learning/index.md

### CODE REVIEW

**Comment by Keno** [comment]
I'm wondering if we could make it more prominent, without being obstrusive. Maybe a small button the one if the sides or something. I'm sure there's prior art somewhere.

**Comment by tlienart** [comment]
Yeah fair enough it's not visible enough. 

I'm not too sure where to place said button though. It could be on the same line as the title, a bit like where the RSS button used to be but right-aligned? Or should it be kept in the footer somewhere and just made more visible there?

**Comment by Keno** [comment]
I was imagining something like a floating action button ala https://materializecss.com/floating-action-button.html

**Comment by tlienart** [comment]
Ok here it is. The button appears on pages that  aren't  the front page or the blog front page as I thought that would be a distraction. Otherwise it appears on all pages provided the width of the page is big enough. Styling etc could be adapted.

Preview should be at https://julialang.netlify.app screenshot below: (bottom right button)

Screen Shot 2020-05-09 at 11 38 54

**Comment by Keno** [comment]
I think the button is a little large. Maybe reduce to 75% of the current size?

**Comment by tlienart** [comment]
sounds good

**Pull request merged**
