### PR TITLE
Add Pluto JSoC projects

### PR DESCRIPTION
**Pull request by fonsp**
As discussed with @aviks & @ViralBShah today, I have added 3 Pluto projects!

I heard that these need to be published soon, so feel free to correct, edit, delete, add, etc the proposals as you see fit!

### CODE REVIEW

**Review by aviks — APPROVED** [review]

**Comment by logankilpatrick** [comment]
Looks great! Thank you again.

**Comment by ViralBShah** [comment]
I think we should separate out Pluto into a separate top-level rather than have it in tooling.

**Comment by ViralBShah** [comment]
I am doing it right now.

**Comment by ViralBShah** [comment]
f05366c636639e7a35c6723846ede5a5c86d03d7

**Pull request merged**
