### PR TITLE
promote Win32 back to tier 1

### PR DESCRIPTION
**Pull request by vtjnash**
We have not had CI issues in a fairly long time[^1], and we do expect it to work and be tested at all times still.

[^1]: https://github.com/JuliaLang/www.julialang.org/commit/55ff318eec7e09e269a3229508e6621f14f9d004

### CODE REVIEW

**Comment by KristofferC** [comment]
CI for windows on 1.8 is borken: https://github.com/JuliaLang/julia/pull/46984

**Comment by vtjnash** [comment]
That is https://github.com/JuliaLang/julia/issues/46940

**Comment by KristofferC** [comment]
Is that really on the 1.8 branch?

**Comment by vtjnash** [comment]
No, that is on master (and i686-linux-gnu), and indeed, also needs to reapply a PR to reproduce the issue. But it appears to be the same, although we were not running win32 CI on buildkite yet at the time of that failure for comparison.

**Comment by DilumAluthge** [comment]
This shouldn't be merged until https://github.com/JuliaCI/julia-buildkite/pull/226 has been merged.

**Comment by KristofferC** [comment]
Just pointing out, that the one who bumps a platform to tier 1 is also signing up to fix any issue that occurs in the future that is unique to that platform :).

**Comment by ViralBShah** [comment]
I feel it is best to leave it at Tier 2...

**Comment by vtjnash** [comment]
It passes as much as other tier 1 platforms (Win64 + linux32), since it shares pretty much all code and issues with one of those 2. We can demote it again just as easily if that ceases to be true.

**Comment by KristofferC** [comment]
> We can demote it again just as easily if that ceases to be true.

What? A tier is not a reflection of the current state of CI. It is a commitment saying that if CI drifts away from what the tier list states then we will not do a release until CI has been fixed.

**Comment by ViralBShah** [comment]
I don't think it is a good idea to promote win32 up again. See-sawing it up and down the tiers is not a good look.

**Comment by vtjnash** [comment]
We can revert. I just didn't want this to conflict with the Win8 PR. And I do think it is fairly stable on CI and still useful to make releases for it

**Pull request merged**
