### PR TITLE
specify google group

### PR DESCRIPTION
**Pull request by apparluk**
Specify use of a Google Group.

### CODE REVIEW

**Comment by timholy** [comment]
I think this kind of missed the point. `group` is being used in two ways, "group of people" and "Google Group." The former is more important---how you email a collection of people is a pretty minor detail.

But it might be worth disambiguating these; want to try a different approach? I might use the word "committee" instead of "group" to refer to the "group of people."

**Comment by logankilpatrick** [comment]
Hey, not sure as to the context of this PR. Feel free to elaborate more if need be.

**Comment by apparluk** [comment]
It's a liability issue, who has access to what information and where is it stored.

It's the similar with the "non-steward members" content.

Consult with counsel.

**Comment by logankilpatrick** [comment]
Thanks for the heads up.

**Comment by apparluk** [comment]
membership lists 7

therefore quorum

would be better than

3+ disinterested stewards (possibly including non-steward members)

**Comment by apparluk** [comment]
@logankilpatrick 

If the developers don't want to inform the community of the use of 3rd Party servers in processing complaints that is their own business.

redacted content as appears at the base of e-mails sent in response to complaints

`You received this message because you are subscribed to the Google Groups "Julia Stewards" group.`

**Pull request closed without merging**
