### PR TITLE
Mentorship for VS Code Extension Project

### PR DESCRIPTION
**Pull request by irahulcse**
Hi, I am Rahul Chandra, GCI Mentor Julia 2020. I would like to apply and work with contributors for VS code extension. I had previously also helped lots of students to work on Julia via editors of their choice.

Thanks

@ChrisRackauckas @MasonProtter

### CODE REVIEW

**Comment by logankilpatrick** [comment]
Cc @davidanthoff

**Comment by irahulcse** [comment]
Hi, @logankilpatrick Any problem regarding the pull request?. It will be my privilege to again work with Julia as a Mentor for GSoC.

**Comment by logankilpatrick** [comment]
Hey @irahulcse Please ping Chris, David, or Mason on Slack if you would like to join them mentoring these projects. Have them open a new PR to add you. Thank you for your interest in helping out, if those projects don't need more mentors, then we can surely find somewhere else for you to help with.

**Comment by davidanthoff** [comment]
So I have to admit I'm slightly confused: I would have assumed that mentors for projects are supposed to be the folks that maintain that project, i.e. essentially own that code? The folks that have a long history of engagement with a project? Or am I misunderstanding how this is supposed to work?

**Comment by ChrisRackauckas** [comment]
Yes, don't ping me on VS Code extension projects. I don't work in this area. I would have no idea what I'm doing. 

Mentors should only be those who are maintainers. If the mentor does not have merge commits, then how could they know they are leading a student to a real PR that could be merged? I do not think this change is okay. The right way to do this is to spend enough time contributing to the project in order to get build the community trust and get merge access.  GSoC is a whole different level from GCI. GCI is high school level quick projects, GSoC is many times done by late stage PhD students who are trying to work with an expert in the field. The profile of this individual shows less expertise in the subject then what I would require a GSoC student to have to get accepted, so how is that a capable mentor? I am all for inclusivity, but this would just not be fair to the students.

**Pull request closed without merging**
