### PR TITLE
Add Why Julia page

### PR DESCRIPTION
**Pull request by logankilpatrick**
Will eventually be linked on the home page with the code example(s).

Waiting on more videos in the playlist.

### CODE REVIEW

**Comment by ViralBShah** [comment]
Do we still want to leave this open?

**Comment by logankilpatrick** [comment]
We can merge or close it, I still think the idea is valid and I'll continue to follow up on it. 

Getting it merged may inspire others to do a video

**Comment by ViralBShah** [comment]
I don't think we should merge with incomplete content. We need a few high quality videos from diverse participants. Some from users, some from developers or well known people and such would greatly help.

We can leave it open.

**Comment by logankilpatrick** [comment]
Can always re-visit if the initiative takes off. Perhaps something to ask of folks for JuliaCon 2021

**Pull request closed without merging**
