### PR TITLE
Add DFTK JSOC project

### PR DESCRIPTION
**Pull request by mfherbst**
Pining @antoine-levitt if he has any comments.

Also I was not too sure where to put the project info. There is a science.md, but then many of the projects are kind of related to science. Happy for feed back if I should place the project somewhere else.

### CODE REVIEW

**Comment by antoine-levitt** [comment]
LGTM!

**Comment by ViralBShah** [comment]
@logankilpatrick @tlienart How do we fix the failing checks?

**Comment by mfherbst** [comment]
Thanks @ViralBShah for the merge!

**Comment by tlienart** [comment]
@ViralBShah seems like GithubAction deprecated `set-env`: 

> Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

looks like they will fully disable that; it's actually @DilumAluthge who knows this stuff (the lines https://github.com/JuliaLang/www.julialang.org/blob/ce5d82154987f397797b1132ae5ae4ee824d1cea/.github/workflows/deploy.yml#L23-L28), Dilum would you have an idea how to bypass this short of using the `ALLOW_UNSECURE_COMMANDS` which doesn't sound too good? thanks 🙌

**Comment by giordano** [comment]
Do you basically want to set a variable in a job and use its value in subsequent jobs?  You can do it with [`fromJSON`](https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#fromjson)

**Comment by DilumAluthge** [comment]
Yeah gimme one sec

**Comment by DilumAluthge** [comment]
@tlienart @ViralBShah https://github.com/JuliaLang/www.julialang.org/pull/1091

**Pull request merged**
