### PR TITLE
[WIP] Re-designed Julia Learning Page

### PR DESCRIPTION
**Pull request by logankilpatrick**
This is an overhaul of the Julia Learning page. The wording on some of the sections is sparse so feel free to suggest things.

### CODE REVIEW

**Comment by logankilpatrick** [comment]
https://julialang.netlify.app/learning/

**Comment by zdroid** [comment]
Those red sections look a bit messy with different top and bottom whitespace:

Screenshot from 2020-06-18 09-40-34

**Comment by ViralBShah** [comment]
Apart from the whitespace issues, I have some content thoughts.

- [ ] I think we should show all the JuliaAcademy classes, and some of the books on this page with icons/pictures.
- [ ] For Youtube, we should mention all the other non-teaching materials - perhaps that is for the community page.
- [ ] For the universities teaching Julia, maybe we should add this image

**Comment by ViralBShah** [comment]
Screen Shot 2020-06-18 at 9 48 07 AM

**Comment by ViralBShah** [comment]
Screen Shot 2020-06-18 at 9 48 19 AM

**Comment by ViralBShah** [comment]
I can probably update the books to add a couple of new ones. I am guessing if we are going to do this, I can share the powerpoint slides, so that we can use the individual images in that to put a set of tiles together.

**Comment by logankilpatrick** [comment]
@ViralBShah I agree with all those suggestions. Adding some images will liven things up. Feel free to post the images here or send them to me on Slack and I'll get them in there unless the ones above are sufficient ^

**Comment by zdroid** [comment]
@ViralBShah It does look very good, but it can't be expanded further, which is a bit of a liability. It also won't display nicely on mobiles, since the image has fixed size and cannot be broken into layout components.

**Comment by ViralBShah** [comment]
I think with books, the images are easy to expand. With universities, not so much. I guess we could just show this list as a collection of some universities, followed by a larger list.

**Comment by zdroid** [comment]
@ViralBShah That's right, I agree with you that not all universities should be presented on the prominent pages. Maybe a separate page for that would work well enough.

But I still don't see much merit of using an image. It is not a suitable form of communication, to merge multiple images into a larger one, when they can be broken down and made into a layout. Such image will be displayed very bad on smaller screens for example.

**Comment by ViralBShah** [comment]
I did not suggest using the image... Just shared it as an example of what I have. I have shared the presentation with the images with Logan.

**Pull request closed without merging**
