### PR TITLE
In Talk to us container changed #JuliaLang to JuliaLang

### PR DESCRIPTION
**Pull request by Atharv0003**
In Talk to us container changed #JuliaLang to JuliaLang

### CODE REVIEW

**Comment by Atharv0003** [comment]
@ViralBShah please check

**Comment by Atharv0003** [comment]
@jishnub please check

**Comment by fredrikekre** [comment]
I always thought it referred to the hashtag.

**Comment by ViralBShah** [comment]
Yeah, `#julialang` is our hashtag on X.

**Pull request closed without merging**
