### PR TITLE
avoid automath/code for now

### PR DESCRIPTION
**Pull request by tlienart**
@ChrisRackauckas please have a look at https://julialang.netlify.com when the build is done to confirm it's what you expect & I'll merge, cheers.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Looks good mostly, except 

and encoded in Julia like:

using DifferentialEquations function lotka_volterra(du,u,p,t) x, y = u α, β, δ, γ = p du[1] = dx = α*x - β*x*y du[2] = dy = -δ*y + γ*x*y end u0 = [1.0,1.0] tspan = (0.0,10.0) p = [1.5,1.0,3.0,1.0] prob = ODEProblem(lotka_volterra,u0,tspan,p)

that's missing a code block for some reason?

**Comment by tlienart** [comment]
will fix

**Comment by tlienart** [comment]
should be all good  now

**Comment by ChrisRackauckas** [comment]
Awesome thanks

**Pull request merged**
