### PR TITLE
Removed the book "mastering and Julia 1.0"

### PR DESCRIPTION
**Pull request by bjrnfrdnnd**
Book seemingly does not exist

### CODE REVIEW

**Comment by tlienart** [comment]
Thanks.

For anyone else stumbling upon this, there  is  https://www.packtpub.com/gb/application-development/mastering-julia  but it's indeed 2015, there does not seem to be a second edition.

**Comment by ViralBShah** [comment]
I am pretty sure a "Mastering Julia 1.0" had been released. @aviks Do you know more? Just curious. Certainly can't see it on the website.

**Comment by aviks** [comment]
No the second edition of this book has not been published, and likely wont be. We should remove all non-1.0 books from the list.

**Comment by ViralBShah** [comment]
That's a good idea - we should remove the old books.

**Comment by PallHaraldsson** [comment]
It seems premature, as I found it here with !.0" at the cover: https://www.goodreads.com/book/show/41838458-mastering-julia-1-0
> Kindle Edition, 463 pages
> Published April 9th 2019 by Packt Publishing

before was published in 2015.

**Comment by tlienart** [comment]
If you find a website where you can buy it I’ll add it back :)

**Comment by PallHaraldsson** [comment]
FYI. Former edition was paperback, and current seems only Kindle (and why was it revoked? it would it get a cover and (empty) goodreads page as meant to be published but never actually was?).

It's very strange, Amazon link at goodreads didn't work (assuming at some point it did), and while I found ASIN, and it's on this website: https://www.synccentric.com/features/upc-asin/?gclid=CjwKCAjwk6P2BRAIEiwAfVJ0rJEnBSbf4JYnSpUnsPew0I1M9Gt9fwInGMMR3EilZ6JdPGcb7EvQYBoCNWkQAvD_BwE

then going to Amazon doesn't work.

https://www.amazon.com/gp/seller/asin-upc-isbn-info.html/ref=sxts_snpl_1_0_dadbf03a-6de4-4724-8cdc-ef3370f16869?pd_rd_w=9gr1v&pf_rd_p=dadbf03a-6de4-4724-8cdc-ef3370f16869&pf_rd_r=X4TESKS87WYC97VR80PK&pd_rd_r=911e97ee-d1f8-4d8f-afa9-f1d0bf3cda42&pd_rd_wg=eqCaQ&qid=1590245182

**Comment by PallHaraldsson** [comment]
It actually at least on German Amazon: https://www.amazon.de/Mastering-Julia-1-0-processing-problems/dp/1788298136

I didn't try to buy it, or see how far I would get. "Kaupt" button where are you...?

**Comment by tlienart** [comment]
I think it would make more sense to just reach out to  the author and ask what's up  than doing archeological work here right? 

(nice find on the German Amazon, though it says: "Derzeit nicht verfügbar. (...)" i.e. not  available + unclear when it'll be)

**Comment by ViralBShah** [comment]
@aviks knows the author, and his comments are based on that.

**Pull request merged**
