### PR TITLE
add a /packages page

### PR DESCRIPTION
**Pull request by StefanKarpinski**

### CODE REVIEW

**Comment by ararslan** [comment]
Might be nice to add a sentence or two on how the provided options here differ, since it's not immediately obvious.

**Comment by StefanKarpinski** [comment]
Since we're redirecting from pkg.julialang.org to a 404 I wanted to get something up ASAP.

**Comment by StefanKarpinski** [comment]
Anyone have any idea how to deploy the site these days? Is merging the PR enough?

**Comment by logankilpatrick** [comment]
Yes

**Comment by StefanKarpinski** [comment]
Ok, well, that's horrifically broken, but I have no idea how to preview locally or see the build preview, so I guess at least there's something when you go to https://pkg.julialang.org now.

**Comment by StefanKarpinski** [comment]
Nope, that's broken too because it redirects to https://julialang.org/packages without the trailing slash which Franklin doesn't consider the same as with the trailing slash, so we're really in an unfortunate state here. I guess anyone going to pkg.julialang.org will just think it's down. Not much I can do about it at the moment.

**Comment by logankilpatrick** [comment]
I got it

**Comment by logankilpatrick** [comment]
#741

**Comment by logankilpatrick** [comment]
https://julialang.netlify.app is where you can see the build previews

**Comment by fredrikekre** [comment]
> Nope, that's broken too because it redirects to https://julialang.org/packages without the trailing slash which Franklin doesn't consider the same as with the trailing slash

I think that is up to the webserver, not the site generator. https://julialang.org/packages redirects to https://julialang.org/packages/ for me at least.

**Pull request merged**
