### PR TITLE
[WIP] Add new D&I Page

### PR DESCRIPTION
**Pull request by logankilpatrick**
This is a WIP update to our D&I page based on current initiatives by folks in the community.

### CODE REVIEW

**Comment by ViralBShah** [comment]
I think there might be a couple of julialang blogs also that @xorJane wrote post JuliaCon with some stats. Also can link to the community surveys that provide some data.

**Comment by ViralBShah** [comment]
I wonder if we should include a chart from Google analytics data on % by gender over time.

**Comment by SaschaMann** [comment]
The sub-pages are all fairly short, I wonder if it might be better to embed them rather than link to them? Makes it easier to get an overview imo.

**Comment by logankilpatrick** [comment]
> The sub-pages are all fairly short, I wonder if it might be better to embed them rather than link to them? Makes it easier to get an overview imo.

The sub-pages have to be built out. They are blank right now.

**Pull request merged**
