### PR TITLE
Update and rename index.html to index.md

### PR DESCRIPTION
**Pull request by logankilpatrick**
Fixes the packages page

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
I don't really get why this was broken, I copied the `learning` directory and then edited...

**Comment by StefanKarpinski** [comment]
But thanks for fixing it for me :)

**Comment by logankilpatrick** [comment]
Must have been an old learning directory as the new one uses markdown

**Comment by StefanKarpinski** [comment]
Seems I was on a branch and did a pull to update which updated nothing, then rebased on top of master, which lead to this broken situation. Thanks for rescuing me.

**Comment by logankilpatrick** [comment]
Also, if you want the url julialang.org/packages rather than julialang.org/packages/ we need to take the file out of the packages folder and make a packages.md file in the root of the repo.

**Comment by StefanKarpinski** [comment]
Our other top-level pages have the trailing slash, so for consistency I think we should do that.

**Comment by fredrikekre** [comment]
> Also, if you want the url julialang.org/packages rather than julialang.org/packages/ we need to take the file out of the packages folder and make a packages.md file in the root of the repo.

What? Both those options should be equivalent (`packages/index.html`).

**Comment by logankilpatrick** [comment]
@fredrikekre I don't make the rules I just play by them :) But actually, all the pages within folder require an extra "/" in order to access them, this seems standard/normal given they are in a subdir

**Comment by fredrikekre** [comment]
> @fredrikekre I don't make the rules I just play by them :)

I don't understand wat you mean. both `/packages.md` and `packages/index.md` should result in the exact same thing, that is `packages/index.html`. The webserver/browser redirects `packages` to `packages/`. If that didn't happen for you then it is probably a caching problem.

**Pull request merged**
