### PR TITLE
Add a script to automatically populate oldreleases.md

### LINKED ISSUE #1702: "Older Releases" page seems pretty out of date
Page: https://julialang.org/downloads/oldreleases/

Latest "old" release listed is 1.5.4.

### PR DESCRIPTION
**Pull request by ararslan**
This uses versions.json to automatically generate the full set of older releases that don't appear on the main downloads page as an HTML table.

Fixes #1702.

### CODE REVIEW

**Comment by giordano** [comment]
Maybe a GitHub Action can be used to keep the page up-to-date (with a workflow dispatch to do it on-demand)?

**Comment by ararslan** [comment]
I guess ideally we want it to be re-generated every time one of the versions in config.md changes. I figured that I'd just do it manually as part of updating that file for a new release since I'm typically the one that makes that change. That's a good point though. At a minimum we could put a comment in config.md saying to rerun the script.

**Comment by giordano** [comment]
https://julialang.netlify.app/previews/pr1706/downloads/oldreleases/ nice!  I wonder if people are really strongly interested in betas and RCs?  Perhaps we can skip them?

**Comment by ararslan** [comment]
Could be convenient to keep them as I've seen cases where people upgrade, notice a difference in the behavior of their code, and want to retry with a previous RC/beta/whatever.

**Comment by ararslan** [comment]
Weird that the table styling doesn't match the downloads page.

**Comment by ararslan** [comment]
I don't really like how much horizontal space the SHA sums take up; on my monitor they make every other column's values line wrap. Not really sure what to do about it though.

**Comment by DilumAluthge** [comment]
Smaller font size?

**Comment by ararslan** [comment]
For that column specifically or for everything?

**Comment by DilumAluthge** [comment]
We could probably do a smaller font size for the whole table, tbh.

And then an even smaller font size for the checksums.

**Comment by ararslan** [comment]
I imagine there's some kind of fancy CSSing that has to happen for that and I, uh, don't know how to do it.

**Comment by DilumAluthge** [comment]
Let's just stick with the existing font size for now?

**Comment by DilumAluthge** [comment]
@ararslan What's the status of this? Is it good to merge (after the merge conflicts are resolved)? Would be nice to get this in.

**Comment by ararslan** [comment]
> Is it good to merge (after the merge conflicts are resolved)?

I believe so. It's a baseline upon which people can improve, if nothing else, but it gets the job done. The primary downsides as implemented in this PR:
- The file still needs to be updated manually, though it's easier now with the script. As Mosè pointed out, this could be improved with a GitHub Action.
- The style used on the old releases page inexplicably doesn't match the main downloads page with this change, at least in the PR preview.
- SHAs are long and ugly.

I've rebased to fix conflicts and rerun the script to include 1.8.0 in old releases.

**Pull request merged**
