### PR TITLE
closes #714

### LINKED ISSUE #714: Editors and Essential Tools headings are not aligned properly
Screen Shot 2020-04-14 at 4 57 47 PM
Screen Shot 2020-04-14 at 4 57 40 PM

### PR DESCRIPTION
**Pull request by tlienart**
preview will be generated at https://julialang.netlify.com 

ref: #714

### CODE REVIEW

**Comment by ViralBShah** [comment]
The preview still looks the same as before. Even in incognito mode.

**Comment by tlienart** [comment]
> The preview still looks the same as before. Even in incognito mode.

that's because you/someone pushed something else which triggered another build that took over unfortunately GA can't be triggered manually.

Screenshots below

Screen Shot 2020-04-15 at 18 24 58

**Comment by tlienart** [comment]
preview is now up to date: https://julialang.netlify.app/

**Comment by ViralBShah** [comment]
Should we merge?

**Comment by tlienart** [comment]
If the result looks like what you wanted, then yes 😄

**Pull request merged**
