### PR TITLE
Add JuliaNonconvex organization

### PR DESCRIPTION
**Pull request by gdalle**

### CODE REVIEW

**Comment by ViralBShah** [comment]
Can you the devs of this org make themselves public? Currently has no public members and some of the repos are empty (on casual browsing). Would be nice to have a logo.

None of this is a strict requirement to add the org here. But perhaps if some cosmetic things about the org are updated, just ping here and I'll merge.

**Comment by gdalle** [comment]
To tell you the truth I'm not a member of the org myself. I just saw it in the new Slack channel dedicated to new packages, and since it's in my research area I though I would add it here ^^

**Comment by mohamed82008** [comment]
The org started 2 days ago, I am still moving code around. I will make myself public but let's hold that PR for a few days till I am done moving stuff from Nonconvex.

**Comment by mohamed82008** [comment]
I think this one is ready to go in now. I am still missing a logo but that's not a show stopper.

**Pull request merged**
