### PR TITLE
Add Flux to organisations.md

### PR DESCRIPTION
**Pull request by DhairyaLGandhi**
cc @ViralBShah

### CODE REVIEW

**Comment by logankilpatrick** [comment]
Really not sure how Flux was not listed already. Thanks for adding this in!

**Comment by ViralBShah** [comment]
Others that need adding are

JuliaTesting
JuliaTokyo
JuliaKorea
CliMA
HolyLab
JuliaPOMDP
JuliaLabs

**Comment by logankilpatrick** [comment]
Done @ViralBShah

**Comment by ViralBShah** [comment]
Gotta figure out a better way to do this. Thanks for adding them for now.

**Pull request merged**
