### PR TITLE
Fix placement of 64-bit ARM on Downloads page

### PR DESCRIPTION
**Pull request by AnAverageHuman**

### CODE REVIEW

**Comment by ViralBShah** [comment]
Thanks!

**Comment by ViralBShah** [comment]
@tlienart While the deploy stage failed (as you had noted before), would it get deployed when I merge?

**Comment by tlienart** [comment]
yes!

**Comment by tlienart** [comment]
(all people who merge are part of the org and so can trigger a GitHub action that relies upon the DEPLOY_KEY; at least that's my understanding)

**Pull request merged**
