### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by logankilpatrick**
Adding English language tag: "Identifying the language of the page allows screen readers to read the content in the appropriate language. It also facilitates the automatic translation of content." per https://wave.webaim.org/report#/https://julialang.org

#458

### CODE REVIEW

**Comment by logankilpatrick** [comment]
I still need to figure out how to test this.

**Comment by ViralBShah** [comment]
Should we merge and see if it works?

**Comment by logankilpatrick** [comment]
If it isn't going to break anything, then yes.

**Comment by logankilpatrick** [comment]
Do these changes propagate to the actual website automatically?

**Comment by ViralBShah** [comment]
Yes, but it takes a few mins. If you want to check right away - pass random different GET parameters: `https://julialang.org?x` etc., in order to force the CDN to be bypassed.

**Comment by logankilpatrick** [comment]
Awesome. Looks like that issue was resolved! 

Best,
Logan Kilpatrick

**Pull request merged**
