### PR TITLE
Slightly modified backsplash

### PR DESCRIPTION
**Pull request by tlienart**
Courtesy of @cormullion 

**Current**
Screen Shot 2020-05-17 at 11 39 43

**Possible new**
Screen Shot 2020-05-17 at 11 39 49

**My opinion**

I like that the lines between triangles are thinner, it's also a bit less dark.

---

Could I have a 👎 to leave things as they are or  a 👍 to merge this one?

### CODE REVIEW

**Comment by zdroid** [comment]
How about a more dark one instead? It gives better contrast to the text.

**Comment by cormullion** [comment]
There are a few comments saying that the current one "is too dark" - perhaps your monitor is very bright? :)

**Comment by zdroid** [comment]
It's actually pretty dark. I am just comparing it to the previous background which was darker and had a bit more contrast.

**Comment by tlienart** [comment]
But, crucially, adjacent triangles are of different colors!!

Anyway it's the kind of stuff where people might never fully agree, would it make sense to run a short poll on discourse or something? (I fear the wave of random unrelated comments we might get)

**Comment by abhishalya** [comment]
I prefer the old one because of the contrast. Maybe we can keep the darkness from old one and reduce the thinkness of lines as per the new one? Maybe we can reach a middle state in terms of darkness too? :P

**Comment by ViralBShah** [comment]
No poll invitations for design stuff please. It's all too subjective. :-)

**Comment by ViralBShah** [comment]
I did think the earlier one was too dark and prefer the lighter colors in the new one.

**Pull request merged**
