### PR TITLE
In "Platform Specific Instructions" -> "macOS", don't recommend that the user use `sudo` when creating the symlink

### PR DESCRIPTION
**Pull request by DilumAluthge**
I don't think this `sudo` is actually necessary, although it would be good for someone to confirm this.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Hmmm. I don't think this is always correct.

**Comment by fredrikekre** [comment]
I think it is needed for all the commands, not just `ln`.

**Comment by DilumAluthge** [comment]
Yeah, I think you are right. I think by default, `/usr/local` is owned by `root` and is read-only to non-`root` users.

**Comment by DilumAluthge** [comment]
https://github.com/JuliaLang/www.julialang.org/pull/1445

**Pull request closed without merging**
