### PR TITLE
sharks blogpost

### LINKED ISSUE #1348: Static html blog post
I've written a tutorial that might be fun to host on the JuliaLang blog. I made it using Pluto and have exported the static HTML which can be found [here.](https://github.com/weymouth/weymouth.github.io/blob/master/Shark.jl.html).

@ViralBShah

### PR DESCRIPTION
**Pull request by tlienart**
cc @weymouth , @ViralBShah 

Please have a look at the preview that'll be attached to this PR in 15 or so minutes navigating to the relevant blog post.

### Notes

The file you had prepared was empty so what I did (and what someone in the future porting a Pluto notebook will need to do) is:

* get the `notebook.jl`
* copy paste the markdown in appropriate locations
* copy paste the code dumping the `begin/end` business into non-evaluated (1) Julia code blocks i.e.

````
```Julia
code here
```
````

* evaluate the code separately and save all figures in an appropriate folder (e.g. here `_assets/blog/2021-08-15-sharks/`) 
* set a page variable to that base path  here `base = "/assets/blog/2021-08-15-sharks/"`
* load all these images in appropriate places with things like ``
* check it looks good and submit a PR

(1) IMO it makes sense to see this blog post as potentially staying for years with potentially the blog post author moving on to other stuff, as a result maintenance of old blog post pages might become pretty annoying if the code gets evaluated on site builds.  This could be mitigated by fixing a Project.toml and Manifest.toml which is easy to do but we could still have problems with Julia versions. For those reasons I think it makes more sense to:

- provide a "frozen" evaluated view
- provide the original script to download (and let the user deal with potential clashes)

closes #1348 

PS: the date doesn't really matter, I just put a reasonable date in the near future since the blog post is pretty good and I imagine we'll merge by then.

### CODE REVIEW

**Comment by tlienart** [comment]
Now live here: https://julialang.netlify.app/previews/pr1349/blog/2021/08/sharks/

**Comment by weymouth** [comment]
I'm sorry you had to do that. I don't know how the file ended up empty (GitHub weirdness?), but I didn't put the code inside Julia blocks like that anyway and I can see you've adjust the text and code at the interactive elements.

I think the post looks good and I am happy with it going up.

**Comment by tlienart** [comment]
Alright cool, I set the publication date to today & will merge, nice blog post :+1:

**Comment by ViralBShah** [comment]
Nice. Thanks all!

**Pull request merged**
