### PR TITLE
Redirecting julialang.org/download to julialang.org/downloads

### PR DESCRIPTION
**Pull request by fungktt**
As seen from the title.

Tested here: https://julialang-test.netlify.com/download/ which redirects to julialang.org/downloads

### CODE REVIEW

**Comment by logankilpatrick** [comment]
Note that this does not appear to be working. JuliaLang.org/download still shows an error 404 for me

**Comment by ViralBShah** [comment]
Same here.

**Comment by ViralBShah** [comment]
Maybe Github pages doesn't like this plugin?

**Comment by ViralBShah** [comment]
I hear that we should be moving to Hugo from Jekyll.

**Comment by ViralBShah** [comment]
We probably should revert this.

**Pull request merged**
