### PR TITLE
add the julia 1.8 release highlight blog post

### PR DESCRIPTION
**Pull request by KristofferC**
Free for all for people to add stuff.

### CODE REVIEW

**Comment by jakobnissen** [comment]
May want to consider mentioning the exciting new effects system enabled by `@assume_effects`

**Comment by jakobnissen** [comment]
Perhaps also https://github.com/JuliaLang/julia/pull/41936

**Comment by IanButterworth** [comment]
Is there a preview of this PR? 

This doesn't work

https://julialang.netlify.app/previews/pr1730/

**Comment by IanButterworth** [comment]
Oh, no, because the PR is from a fork

**Comment by KristofferC** [comment]
Oh, I guess I should have pushed to this repo. It's pretty easy to preview it locally though.

**Comment by KristofferC** [comment]
I'll merge this now since the binaries are updated but if someone feels something more should be added, it can easily be added post merge.

**Comment by PallHaraldsson** [comment]
Note again, "no matter what the package man" (and no period), bad grammar and not even sure ending with right word. I wasn't confident what is referred to.

**Pull request merged**
