### PR TITLE
Add ARM binaries to downloads page

### PR DESCRIPTION
**Pull request by ararslan**
Fixes https://github.com/JuliaLang/julia/issues/30870.

### CODE REVIEW

**Comment by ViralBShah** [comment]
Looks great. I think eventually we want to maintain the tiers only on one place, but let's merge away for now.

**Comment by jekbradbury** [comment]
There's a decent amount of scrolling needed to find the actual links now. I wonder if you'll see a (tiny) drop in the download stats...

**Comment by ararslan** [comment]
I would be surprised if anyone would give up on downloading altogether due to scrolling, but you're right, this introduces a nontrivial amount of non-links to a page people would go to for links. Perhaps we should look at how other projects structure their downloads page while making levels of support clear.

**Comment by staticfloat** [comment]
Thanks Alex!

**Comment by ViralBShah** [comment]
I moved the supported platforms to the bottom. I think it works well there. What we need is a link on the top (next to platform-specific instructions to the tiers table at the bottom).

**Pull request merged**
