### PR TITLE
Add AMD GPUs as a supported platform (Tier 3 - experimental)

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by ViralBShah** [comment]
Probably should also update the URLs here: https://juliagpu.org/rocm/

**Comment by DilumAluthge** [comment]
Yep. Which URLs are broken for you? For me, the `NVIDIA CUDA` link is broken, but all the other links seem correct.

**Comment by DilumAluthge** [comment]
https://github.com/JuliaGPU/juliagpu.org/pull/8

**Comment by ViralBShah** [comment]
Ah sorry - not broken - but all those repos moved to the JuliaGPU org.

**Comment by DilumAluthge** [comment]
Ah yes, I'll fix those as well.

**Comment by DilumAluthge** [comment]
https://github.com/JuliaGPU/juliagpu.org/pull/9

**Pull request merged**
