### PR TITLE
Add vim, emacs and sublime to IDE list 

### PR DESCRIPTION
**Pull request by ranjanan**

### CODE REVIEW

**Comment by ViralBShah** [comment]
Can we remove sublime?

**Comment by KristofferC** [comment]
I don't think we should include the sublime plugin since it ihas beem unmaitained for many years.

**Comment by ranjanan** [comment]
No, it's as well if not better maintained than julia-vim.

**Comment by ViralBShah** [comment]
I thought @quinnj said he doesn't maintain it at all. The emacs plugin has many users and maintainers.

**Comment by ViralBShah** [comment]
Let's see how this looks.

**Comment by ViralBShah** [comment]
I see we need a 6th one for symmetry.

**Comment by ViralBShah** [comment]
@mbauman Can we have your magic here to reduce file sizes?

**Pull request merged**
