### PR TITLE
Add a blog to report the Julia User Meetup in Beijing 2019

### PR DESCRIPTION
**Pull request by findmyway**
This is the Chinese version of the report about the Julia User Meetup in Beijing 2019/08/24.

@Roger-luo  and I will provide an English version soon.

### CODE REVIEW

**Comment by ViralBShah** [comment]
Let's simultaneously publish them if possible. Can you cross-link them from each other?

**Comment by findmyway** [comment]
Sure, will do.

**Comment by Roger-luo** [comment]
I put the English post and a polished Chinese version in #444. let's close this one?

**Comment by findmyway** [comment]
Okay

**Pull request closed without merging**
