### PR TITLE
Center GitHub star button vertically

### PR DESCRIPTION
**Pull request by zdroid**
Before:
Annotation 2020-08-03 201545

After:
Annotation 2020-08-03 201544

### CODE REVIEW

**Comment by logankilpatrick** [comment]
I'm having a really hard time seeing the difference. Can you point out what has changed in the images?

**Comment by zdroid** [comment]
@logankilpatrick You must be blessed not to have OCD like me... :laughing:  It's the star button's position in the right, it was moved ~5-10px lower.

**Comment by giordano** [comment]
> I'm having a really hard time seeing the difference.

Open the two images in two tabs and switch between them.

> Can you point out what has changed in the images?

I think the GitHub icon is now centred compared to the "Download" and "Documentation" buttons

**Comment by ViralBShah** [comment]
I like it better this way too.

**Pull request merged**
