### PR TITLE
add juliaup in platform.md

### PR DESCRIPTION
**Pull request by heliosdrm**
According to @davidanthoff  in https://discourse.julialang.org/t/julia-v1-6-3-has-been-released/68737/7, "the Windows version is really not an experiment anymore".

### CODE REVIEW

**Comment by DilumAluthge** [comment]
1. Juliaup lives in the JuliaLang GitHub organization
2. Juliaup uses the official release binaries

So I don't know if it belongs in the "Unofficial Binaries" section. I would instead make a separate section (immediately preceding the "Unofficial Binaries" section) specifically for Juliaup.

**Comment by heliosdrm** [comment]
Or rather at the end of the "Windows" section?

**Comment by DilumAluthge** [comment]
Eventually, Juliaup will support Windows, Linux, and macOS.

So, actually, I think it makes the most sense to put Juliaup in the "Cross-platform installer" section, the same section that talks about `jill.py`.

**Comment by logankilpatrick** [comment]
Look good, thank you!

**Pull request merged**
