### PR TITLE
add map of local communities

### PR DESCRIPTION
**Pull request by lucaferranti**
Closes: #1871

image

### CODE REVIEW

**Comment by lucaferranti** [comment]
Once it's merged we could advertise in `#community` on slack to get the map more populated :sunglasses:

**Comment by lucaferranti** [comment]
@TheCedarPrince I saw you self-assigned to this. Anything missing from your side or can we merge this? :)

**Comment by TheCedarPrince** [comment]
Ah! I marked this to review when I am back from vacation as I can see this feeding into the general mentoring initiative and mentoring discussion that spawned out of JuliaCon 2024's Diversity Dinner and Discussion. I don't want to be a block because I get back July 26th-ish and then woas planning to do a full review @lucaferranti and @DilumAluthge -- I think it is a grat idea and wanted to combine with efforts in the #mentoring channel in the Julia Slack.

**Comment by ViralBShah** [comment]
Can we add: https://www.meetup.com/julia-cajun/

**Comment by lucaferranti** [comment]
@ViralBShah added

**Review by TheCedarPrince — APPROVED** [review]
I reviewed the code, pulled your fork down locally and checked everything out. Way to go! This is great and has my approval! I will go ahead and merge this -- thanks @lucaferranti !

**Comment by lucaferranti** [comment]
@TheCedarPrince thanks! I will announce this in #community in slack to get more communities. Let's fill the map with julia local communities 😎

**Comment by ViralBShah** [comment]
We should get a few more communities added quickly because it looks a bit sparse otherwise.

**Pull request merged**
