### PR TITLE
Add RL algorithms section in GSoC project list

### PR DESCRIPTION
**Pull request by findmyway**

### CODE REVIEW

**Comment by logankilpatrick** [comment]
Thanks! Looks like an interesting project.

**Comment by findmyway** [comment]
Thanks!
🚀 🚀 🚀

**Comment by RajGhugare19** [comment]
@findmyway What do you mean by scalable distributed RL. Is it something related to this - https://arxiv.org/pdf/1707.06887.pdf
Or Are you saying in the sense of centralised and distributed training in mult-agent envs?

**Comment by findmyway** [comment]
Hi @RajGhugare19 ,

You can create an issue [here](https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/issues) for discussions if you are interested in this project 😃 

<hr>

> Or Are you saying in the sense of centralised and distributed training in mult-agent envs?

Yes. Here scalable distributed RL is different from distributinal RL. [This issue](https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/issues/87) is a step toward this direction.

**Pull request merged**
