### PR TITLE
Taija gsoc updates

### PR DESCRIPTION
**Pull request by pat-alt**
Adds another proposal to the Taija GSoC project list. 

cc @svilupp feel free to edit or lift as is and then copy over to JuliaGenAI

### CODE REVIEW

**Comment by svilupp** [comment]
Thank you for creating the shortcut in JuliaGenAI!

**Comment by svilupp** [comment]
Shall we tag Jacob for review?

**Comment by pat-alt** [comment]
Yup, just added one more small update. @TheCedarPrince we have one more GSoC proposal that will be offered jointly by JuliaGenAI and Taija.

**Comment by TheCedarPrince** [comment]
I love seeing collaborations come up! This is now merged @svilupp and @pat-alt ! :smile:

**Pull request merged**
