### PR TITLE
GSoC: Rust-Julia HTTP interop project (for Pluto)

### PR DESCRIPTION
**Pull request by fonsp**
cc @aviks @pangoraw

### CODE REVIEW

**Comment by giordano** [comment]
You nerdsniped me: https://github.com/JuliaPackaging/Yggdrasil/pull/4448.  Note: this isn't going to work on Musl-based systems and on 32-bit Windows, no way around these limitations.

**Comment by fonsp** [comment]
@giordano 🎉🙏 lots of love! So cool how easily Julia's ecosystem can distribute binaries!

@pangoraw will be better at explaining this, but the main challenge in our proposal will be the interoperability of async event handlers (event = incoming HTTP request) and shared memory/streams... *Or can I nerdsnipe you into that as well?* 😯

**Comment by giordano** [comment]
> _Or can I nerdsnipe you into that as well?_ :hushed:

No, I don't think so :stuck_out_tongue:

**Comment by Pangoraw** [comment]
> You nerdsniped me: [JuliaPackaging/Yggdrasil#4448](https://github.com/JuliaPackaging/Yggdrasil/pull/4448). Note: this isn't going to work on Musl-based systems and on 32-bit Windows, no way around these limitations.

Awesome, thanks! :tada:

**Comment by logankilpatrick** [comment]
This looks great!

**Comment by lucifer1004** [comment]
I believe that none of you have actually tested the generated package, because the C API is not compiled! See the doc of hyper [here](https://docs.rs/hyper/latest/hyper/ffi/index.html).

I have just made a [PR](https://github.com/JuliaPackaging/Yggdrasil/pull/4678).

**Comment by fonsp** [comment]
Wow, awesome! We would love to have you work with us @lucifer1004 , through GSoC or otherwise! Have you considered applying?

**Comment by lucifer1004** [comment]
Actually, I have started working on this, but I cannot ensure that I have enough time to finish it.

**Comment by fonsp** [comment]
Exciting! Feel free to email me (fons@plutojl.org) or paul (paul@plutojl.org) to if you ever want to look at it together :)

**Pull request merged**
