### PR TITLE
Fix delimit for research packages

### PR DESCRIPTION
**Pull request by abhishalya**
Closes https://github.com/JuliaLang/www.julialang.org/issues/614

### CODE REVIEW

**Comment by ViralBShah** [comment]
Please merge if this is good to go.

**Comment by thofma** [comment]
Does this also fix the case sensitivity issue? If not, then this should not close #614.

**Comment by ViralBShah** [comment]
Or open a separate issue for case sensitivity? Apparently, this is something about hugo itself.

**Comment by thofma** [comment]
I will open a new issue then.

**Pull request merged**
