### PR TITLE
Removed slogan + shallow banner

### PR DESCRIPTION
**Pull request by tisztamo**
As discussed in #982

### CODE REVIEW

**Comment by ViralBShah** [comment]
Merging to see how it feels.

**Comment by fredrikekre** [comment]
Looks better with `The Julia Language` IMO. Looks a bit short now, and a bit weird with the logo in the header just there, so it reads like "Julia Julia".

Screenshot from 2020-09-12 00-22-28

---

Screenshot from 2020-09-12 00-22-52

**Comment by artkuo** [comment]
It would be nice to have "language" appear somewhere in top half of landing page. Right now, the first few lines say `julia`, `Julia`, `Julia in a Nutshell`, followed by "Julia was designed to be..." and "Julia programs compile..." The naive reader still doesn't know what it is, and it's only implicit that it's a language. It's not mentioned that it's great for technical computing and data science (among others). Perhaps the previous slogan is overly specific or stale, but _some_ slogan would be beneficial, and should be relatively high up.

**Comment by fredrikekre** [comment]
Perhaps `The Julia Programming Language`?
Screenshot from 2020-09-12 00-30-22

**Comment by logankilpatrick** [comment]
Done @fredrikekre

**Comment by ViralBShah** [comment]
Yeah, just "Julia" was not working. "The Julia Programming Language" is much nicer.

**Pull request merged**
