### PR TITLE
Changed second main link from "Documentation" to "Learn"

### PR DESCRIPTION
**Pull request by sylvaticus**
https://discourse.julialang.org/t/suggestion-change-documentation-to-learn-as-the-second-main-button-on-julialang-org/89929

### CODE REVIEW

**Comment by jd-foster** [comment]
This is a variant/duplicate of #1675.
FWIW, I agree with your suggestion, but to have Documentation as the third button.

**Comment by logankilpatrick** [comment]
I have a hard time seeing how moving the order on these links will actually help users. See some other sites for examples of this similar approach:
- https://numpy.org
- https://jupyter.org

I don't think this will move the needle at all IMO

**Comment by logankilpatrick** [comment]
Learn is directly next to the docs tab, so users are as close as they can get!

**Comment by sylvaticus** [comment]
Up to you, but in both the links you posted, when one click on the "main button" ("get started" in Numpy) or ("Install Jupyter hub") in Jupyter will have:
- a page with the same navigation bar, footer and style as the home page and rest of the site
- a page with toward actionable practical instruction to start using the  "product"

I just think that currently the (new) user is lost when she click on the second link.

image

(secondary problems: (a) no link back to the home page, (b) column should be centered)

Perhaps my problem is only aesthetic, but .. it just looks odd :-|

**Comment by logankilpatrick** [comment]
I added something to this effect here: https://github.com/JuliaLang/julia/pull/47646

**Comment by logankilpatrick** [comment]
And note that I also have an open issue to make use of the extra area on the right side.

**Comment by logankilpatrick** [comment]
I light of the other PR's we have open, I am going to close this. Open to more discussion around how we can get folks to the learning resources faster but it just doesn't seem like this would specifically be the right move. Thanks for the thought on this!

**Pull request closed without merging**
