### PR TITLE
Add "Be Open" section to CoC

### PR DESCRIPTION
**Pull request by logankilpatrick**
Inspired by: https://numpy.org/code-of-conduct/ and based on the conversation here: https://github.com/JuliaLang/www.julialang.org/issues/1235 

I think codifying this in the DNA of the community will help the sustainability of the ecosystem and language. CC: @JuliaLang/stewards Should we ask for public comments on this like @Keno did on the Researchers section?

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
I don't know, this seems like move of an aspirational value than something that we should require of people. What about people who are introverted and just want to ask some question and get an answer with as little fuss as possible? I would say that they should not ask specific people directly unless those people have advertised that this is ok to do, but I don't see why we should force people to "be open".

**Comment by StefanKarpinski** [comment]
Note that the NumPy version is a statement about what the project's values are and what the project strives to be like — it does not tell other people that they need to be open.

**Comment by logankilpatrick** [comment]
Is there a way you think this could be phrased to allow flexibility but still re-enforce the idea that we want things to be open? In my opinion, there are already discussions happening on places like Slack where the people choose to talk there not because they are introverted but because it is easy (this could be false, just my narrow perspective). I tried to leave things open ended by saying "Where possible, we ask that"

**Comment by Kolaru** [comment]
In its current formulation the new paragraph feels rather intrusive to me. It sounds to me like it is saying I should not discuss Julia privately, ever. The Numpy version avoid that by scoping this advice to only discussion related to the project. For julia this could be replaced by "discussions pertaining to a community project".

Along a similar line, I think it would be worth scoping the paragraph around how the private channels of discussion of the julia's community are expected to be used. Especilly since two paragraphs before, there is a line about confidentiality when contacting a steward.

On a different, it feels like a tool like Slack does not really go in the direction described here: there is no persistence of the content, the content's discoverability is low, and finding the tool in the first place may not be obvious. I hardly consider it to be a pulic platform to begin with. So I have a hard time understanding how this CoC paragraph and e.g. Slack would interact.

**Comment by logankilpatrick** [comment]
Part of the motivation for this is specifically making it part of our community structure to move away from mediums in which content disappears (or at least not using them for important discussions). Without specifically calling out Slack, it would indeed make the heavy use of it against this "Open" ideal.

**Comment by KristofferC** [comment]
While that might be a good idea it feels a bit "harsh" to put that into the CoC for how people in the julia community should behave. Remember it is a "code" and it is under the "We expect the following standards to be observed and upheld by all participants in any community forum" heading. 

Also, I think openness and "permanentness" are kind of two different things. For example, I would consider the Julia slack to be open.

**Comment by MasonProtter** [comment]
Yeah, perhaps a better avenue for something like this would be a separate "statement of values" instead of putting it in the code of conduct. If you put things into the CoC that we have no plan or mechanism to enforce, then I'd say that weakens the rest of the CoC because it makes everything seem more aspirational rather than enforce rules of engagement.

**Comment by logankilpatrick** [comment]
Closing based on feedback

**Pull request closed without merging**
