### PR TITLE
Add preview video for rr post

### PR DESCRIPTION
**Pull request by Keno**
@tlienart how do I add extra `meta` tags on a per-page basis? This would have to go in as an `og:video` tag on the rr post page.

### CODE REVIEW

**Comment by Keno** [comment]
cc @ViralBShah who'd requested a video preview for social media

**Comment by tlienart** [comment]
Just modify `_layout/head.html` and put the meta stuff in a `{{ispage /blog/2020/...}} ... {{end}}`

Filling `/...` with the rest of the path to your blog post

**Comment by Keno** [comment]
I think it would be better to allow that to be set on each blog page, since Ideally we'd want to set relevant meta tags on a per-post basis. Editing the head HTML for each post seems like a suboptimal solution.

**Comment by ViralBShah** [comment]
Right setting it per blog page would be ideal, if possible.

**Comment by tlienart** [comment]
Ok that’s also doable, can you just tell me the precise HTML you would like to appear? We can just have a local page var on blog posts which, if defined, gets displayed in the head. Looks like

`{{ifdef meta}} ... HTML ... {{end}}`

And the HTML can be shaped by the meta var.

**Comment by Keno** [comment]
Allowing arbitrary meta tags seems most general. There's a bunch of interesting ones not just video. See https://ogp.me/

**Comment by tlienart** [comment]
Please see #776

**Pull request merged**
