### PR TITLE
Now 3000 packages

### PR DESCRIPTION
**Pull request by PallHaraldsson**
"13 million times and is used at more than 1,500 universities." https://www.hpcwire.com/off-the-wire/julia-computing-brings-machine-learning-in-julia-workshop-to-prague/

### CODE REVIEW

**Comment by PallHaraldsson** [comment]
I was going by: https://github.com/JuliaRegistries/General/blob/master/Registry.toml

I see some are _jll packages.

**Comment by giordano** [comment]
> I see some are _jll packages.

Around 240

**Comment by logankilpatrick** [comment]
I think JC auto-updates their website or have someone do it every month https://juliacomputing.com

**Comment by logankilpatrick** [comment]
So that is what I usually go by

**Comment by logankilpatrick** [comment]
Thanks @PallHaraldsson @giordano !

**Comment by PallHaraldsson** [comment]
@giordano "Around 240"

Thanks, now 264 _jll packages.

I see we could now change on the website to "over 2900" pacakges, assuming we register the new packages waiting with PRs at https://github.com/JuliaRegistries/General/blob/master/Registry.toml

I count from the number of lines there: 3170-13-(528/2) = 2893 and then 14 new waiting.

Most _jll packages are redundant, e.g. HDF5_jll, but not e.g. utf8proc_jll, while I guess such are rare.

**Pull request merged**
