### PR TITLE
Add in auto platform detection on downloads page.

### PR DESCRIPTION
**Pull request by logankilpatrick**

### CODE REVIEW

**Comment by logankilpatrick** [comment]
TODO: 
- [ ] Test on mobile platforms
- [ ] Test on Linux
- [ ] Get design feedback
- [ ] Figure out what other minimum info we want on this page

**Comment by logankilpatrick** [comment]
@tlienart does anything here look glaringly wrong? This works locally for me but is not detecting the platform in the build preview now that it's deployed.

**Comment by tlienart** [comment]
I'm not familiar with this so can't help much :) but if it doesn't work in the preview I doubt it'll work live 😕

**Comment by ViralBShah** [comment]
Should we close this?

**Comment by logankilpatrick** [comment]
Sure, I'll come back to it when I have more time.

**Comment by PallHaraldsson** [comment]
I like it, but shouldn't we be emphasizing juliaup (soon)? Is it worth it do do much work for the download page then? I use juliaup on Linux and it seems stable...

**Comment by PallHaraldsson** [comment]
```
ubuntu@ubuntu:~$ julia
Command 'julia' not found, but can be installed with:
sudo snap install julia
```

That's aweful advice, FYI, better:
Command 'julia' not found, but can be installed with:
sudo snap install juliaup
```

or take over the julia package to switch to juliaup, then it could be snap still, because the downloaded julia wouldn't be.

**Comment by LilithHafner** [comment]
This has gone stale enough that it may be worth starting a new PR. Further, once we start recommending juliaup, the explicit download links will become targeted toward folks who opt out of juliaup's automation and those users may also prefer to see a full list of available downloads.

**Pull request closed without merging**
