### PR TITLE
Add few changes suggested by tota11y

### PR DESCRIPTION
**Pull request by abhishalya**
This adds few changes suggested by [tota11y](https://khan.github.io/tota11y/), an accessibility visualization toolkit.

Resolves https://github.com/JuliaLang/www.julialang.org/issues/491

### CODE REVIEW

**Comment by abhishalya** [comment]
Preview -> https://test_tota11y--julialang-preview.netlify.com/

**Comment by abhishalya** [comment]
**Do not merge** until I remove https://github.com/JuliaLang/www.julialang.org/pull/527/commits/706652782e575e01fb6689855d445a1c4dace037.

This commit is only included so that the reviewers can check the output of tota11y themselves on the [deploy preview](https://test_tota11y--julialang-preview.netlify.com/).

**Comment by logankilpatrick** [comment]
Hey, can you add in what changes under the hood were made and screenshots from Tota11y showing the before and after?

**Comment by abhishalya** [comment]
@logankilpatrick You check the preview itself, the tool is available there. For before, I can add screenshots.

**Comment by abhishalya** [comment]
@logankilpatrick Got a better idea, see the old site with tota11y [here](https://old_tota11y--julialang-preview.netlify.com/).

**Comment by abhishalya** [comment]
Also please see the commits, the reason I made separate commits is because it would be easy to understand. But here are the changed listed:

- Colour changes to manage contrast ratio:
  - Colour of the `Download` button on homepage is changed to slightly more darker colour.
  - Added an inline style to change the colour of links in `footer.html` and `common.html`
  - Changed link colour to slightly more darker colour.
  - Changed nav-links to slightly darker gray.
  - Changed colour of `article-data` to slightly darker shade.
  - Changed colour of red button to a slightly darker shade.
- Heading elements changed to manege consecutive elements (`h1 -> h2 -> h3`)
  - `community/indexhtml` -> `h2` -> `h1`
  - `learning/index.html` -> `h3` -> `h2`
  - `research/index.html` -> `h2` -> `h1`
- Fixed some links to use https.

**Comment by abhishalya** [comment]
Done! @logankilpatrick

**Pull request merged**
