### PR TITLE
Drop JuliaCon container

### PR DESCRIPTION
**Pull request by zdroid**
I know that golang has video display on its frontpage, but it's not really that appealing. I doubt anyone comes to the frontpage to see the videos, and if you actually want to see them, you're better off opening them in the new tab. Also, embedding YouTube videos slows down the page load substantially.

Source: https://github.com/JuliaLang/www.julialang.org/issues/800#issuecomment-627886783

### CODE REVIEW

**Comment by ViralBShah** [comment]
Why did we drop this? We get a huge amount of video views from this.

**Comment by ViralBShah** [comment]
Let's revert this. For major changes it would be good to let the PRs be open some time to gather feedback.

**Comment by tlienart** [comment]
sorry for the over-enthusiastic merge, I'll bring it back

**Comment by zdroid** [comment]
@ViralBShah Right, I agree. I thought it's not really that prominent since it's not on the top of the page. I'll try to find another way for that section to be redesigned.

**Comment by logankilpatrick** [comment]
~ 33% of all our youtube traffic comes from external sources and ~40% of those external sources are the website.

**Comment by ViralBShah** [comment]
Thank you. There was a PR that tried to load the video async.

**Pull request merged**
