### PR TITLE
Newer Julia installers come with an option to `Add Julia to PATH` (Windows)

### PR DESCRIPTION
**Pull request by ven-k**

### CODE REVIEW

**Comment by logankilpatrick** [comment]
Can someone with windows confirm this?

**Comment by sbomsdorf** [comment]
Confirmed on Win10 and Win11 with current Julia 1.7.1 and the LTS (1.6.5) installer. Both have "Add Julia to PATH" checkbox.

**Comment by ven-k** [comment]
Recently I have been using [juliaup](https://github.com/JuliaLang/juliaup) as I juggle between Julia  versions 1.6.5 and 1.7.1. And maintaining multiple versions is quite cumbersome in Windows. Should I mention this as something "Advanced Users" should try? (However the repo description-"An experimental Julia version manager" clearly states its experimental)

**Comment by ViralBShah** [comment]
Let's merge this and mention `juliaup` when it is ready.

**Pull request merged**
