### PR TITLE
replace `---` with the correct en-dash

### PR DESCRIPTION
**Pull request by vtjnash**

### CODE REVIEW

**Comment by ararslan** [comment]
Shouldn't that be — rather than –?

**Comment by ViralBShah** [comment]
I am not an expert on dashes, but pasting @ararslan's dash into the PR did not change how it looked. If the dash overlords want to correct this further, I won't stop them.

**Comment by vtjnash** [comment]
Alex is right, "work—and" might be the more common style, over "work – and" or "work — and" (
http://en.wikipedia.org/wiki/Dash#En_dash_versus_em_dash)

**Comment by ararslan** [comment]
Jameson is dash overlord confirmed

**Pull request merged**
